// Code generated by woco, DO NOT EDIT.

package oas

import (
	"github.com/woocoos/msgcenter/pkg/push"
)

// PostPushRequest is the request object for (POST /push)
type PostPushRequest struct {
	// PostPushRequestBody Push data is for notify clients.
	*push.Data `json:",inline"`
}
