appName: msgcenter
version: 0.0.1
development: true
log:
  withTraceID: true
  cores:
    - level: info
  rotate:

jwt: &jwt
  signingMethod: "HS256"
  signingKey: "secret"

web:
  server:
    addr: 127.0.0.1:10074
  engine:
    routerGroups:
      - default:
          middlewares:
            - cors:
                allowOrigins: ['*']
                allowHeaders: ["*"]
            - accessLog:
                exclude:
                  - IntrospectionQuery
            - recovery:
            - errorHandle:
                message: "系统内部异常，请联系管理员"
      - graphql:
          basePath: "/graphql"
          middlewares:
            - graphql:
                group: "/graphql"
                withAuthorization: false
                publicErrorMsg: "系统内部异常，请联系管理员"
                appCode: "msg"
                middlewares:
                  operation:
                    - tenant:
                    - jwt: *jwt
                    - tokenSign: # 利用IDE开发时,可注释
                header: ## dev mode, remove in production, set the value in your .env.local
                  X-Tenant-ID: ${TENANT}
                  Authorization: "${AUTHORIZATION}"

store:
  msgcenter:
    driverName: mysql
    dsn: "root:@tcp(localhost:3306)/msgcenter?parseTime=true&loc=Local"
  redis: &redis
    addrs:
      - 127.0.0.1:6379
    db: 1

# 消息WebSocket
webSocket:

errors:
  errorMap:
    "missing or malformed jwt": "认证信息缺失，请重新登录"
    "invalid or expired jwt": "登录已过期，请重新登录"
    "invalid jwt claims": "认证信息无效，请重新登录"
