appName: msgcenter
version: 0.0.1
development: true
log:
  withTraceID: true
  traceIDKey: "traceId"
  cores:
    - level: info
      disableStacktrace: true
      encoderConfig:
        timeKey: "@timestamp"
        messageKey: "message"
        callerKey: "file"
  rotate:
    maxsize: 10
    maxage: 10
    maxbackups: 20
    localtime: true

jwt: &jwt
  signingMethod: "HS256"
  signingKey: "secret"

web:
  server:
    addr: 127.0.0.1:10074
  engine:
    routerGroups:
      - default:
          middlewares:
            - cors:
                allowOrigins: ['*']
                allowHeaders: ["*"]
            - accessLog:
                exclude:
                  - IntrospectionQuery
            - recovery:
            - errorHandle:
      - graphql:
          basePath: "/graphql"
          middlewares:
            - graphql:
                group: "/graphql"
                withAuthorization: false
                appCode: "msg"
                middlewares:
                  operation:
                    - tenant:
                    - jwt: *jwt
                    - tokenSign: # 利用IDE开发时,可注释
                header: ## dev mode, remove in production, set the value in your .env.local
                  X-Tenant-ID: ${TENANT}
                  Authorization: "${AUTHORIZATION}"

store:
  msgcenter:
    driverName: mysql
    dsn: "root:@tcp(localhost:3306)/msgcenter?parseTime=true&loc=Local"
  redis: &redis
    addrs:
      - 127.0.0.1:6379
    db: 1

entcache:
  level: context

# 消息WebSocket
webSocket: