// Code generated by ent, DO NOT EDIT.

package org

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the org type in the database.
	Label = "org"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOwnerID holds the string denoting the owner_id field in the database.
	FieldOwnerID = "owner_id"
	// FieldKind holds the string denoting the kind field in the database.
	FieldKind = "kind"
	// FieldParentID holds the string denoting the parent_id field in the database.
	FieldParentID = "parent_id"
	// FieldPath holds the string denoting the path field in the database.
	FieldPath = "path"
	// EdgeMsgAlerts holds the string denoting the msg_alerts edge name in mutations.
	EdgeMsgAlerts = "msg_alerts"
	// Table holds the table name of the org in the database.
	Table = "org"
	// MsgAlertsTable is the table that holds the msg_alerts relation/edge.
	MsgAlertsTable = "msg_alert"
	// MsgAlertsInverseTable is the table name for the MsgAlert entity.
	// It exists in this package in order to avoid circular dependency with the "msgalert" package.
	MsgAlertsInverseTable = "msg_alert"
	// MsgAlertsColumn is the table column denoting the msg_alerts relation/edge.
	MsgAlertsColumn = "tenant_id"
)

// Columns holds all SQL columns for org fields.
var Columns = []string{
	FieldID,
	FieldOwnerID,
	FieldKind,
	FieldParentID,
	FieldPath,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Org queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByOwnerID orders the results by the owner_id field.
func ByOwnerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwnerID, opts...).ToFunc()
}

// ByKind orders the results by the kind field.
func ByKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKind, opts...).ToFunc()
}

// ByParentID orders the results by the parent_id field.
func ByParentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldParentID, opts...).ToFunc()
}

// ByPath orders the results by the path field.
func ByPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPath, opts...).ToFunc()
}

// ByMsgAlertsCount orders the results by msg_alerts count.
func ByMsgAlertsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newMsgAlertsStep(), opts...)
	}
}

// ByMsgAlerts orders the results by msg_alerts terms.
func ByMsgAlerts(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMsgAlertsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newMsgAlertsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MsgAlertsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, MsgAlertsTable, MsgAlertsColumn),
	)
}
