package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"

	"github.com/woocoos/msgcenter/api/graphql/generated"
	"github.com/woocoos/msgcenter/api/graphql/model"
)

// DeviceConnected is the resolver for the deviceConnected field.
func (r *queryResolver) DeviceConnected(ctx context.Context, deviceID string) (bool, error) {
	if r.PubSub == nil {
		return false, nil
	}
	return r.PubSub.HasDeviceConnection(deviceID), nil
}

// Message is the resolver for the Message field.
func (r *subscriptionResolver) Message(ctx context.Context) (<-chan *model.Message, error) {
	return r.PubSub.Subscribe(ctx, string(SubTopicMessage))
}

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type subscriptionResolver struct{ *Resolver }
