// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/woocoos/knockout-go/ent/schemax/typex"
	"github.com/woocoos/msgcenter/ent/appdictitem"
)

// AppDictItem is the model entity for the AppDictItem schema.
type AppDictItem struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 租户ID,空为全局字典
	OrgID int `json:"org_id,omitempty"`
	// 关联代码,由app_code和dict_code组成
	RefCode string `json:"ref_code,omitempty"`
	// 字典值唯一编码,生效后不可修改.
	Code string `json:"code,omitempty"`
	// 名称
	Name string `json:"name,omitempty"`
	// 状态
	Status       typex.SimpleStatus `json:"status,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AppDictItem) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case appdictitem.FieldID, appdictitem.FieldOrgID:
			values[i] = new(sql.NullInt64)
		case appdictitem.FieldRefCode, appdictitem.FieldCode, appdictitem.FieldName, appdictitem.FieldStatus:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AppDictItem fields.
func (adi *AppDictItem) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case appdictitem.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			adi.ID = int(value.Int64)
		case appdictitem.FieldOrgID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field org_id", values[i])
			} else if value.Valid {
				adi.OrgID = int(value.Int64)
			}
		case appdictitem.FieldRefCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ref_code", values[i])
			} else if value.Valid {
				adi.RefCode = value.String
			}
		case appdictitem.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				adi.Code = value.String
			}
		case appdictitem.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				adi.Name = value.String
			}
		case appdictitem.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				adi.Status = typex.SimpleStatus(value.String)
			}
		default:
			adi.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AppDictItem.
// This includes values selected through modifiers, order, etc.
func (adi *AppDictItem) Value(name string) (ent.Value, error) {
	return adi.selectValues.Get(name)
}

// Update returns a builder for updating this AppDictItem.
// Note that you need to call AppDictItem.Unwrap() before calling this method if this AppDictItem
// was returned from a transaction, and the transaction was committed or rolled back.
func (adi *AppDictItem) Update() *AppDictItemUpdateOne {
	return NewAppDictItemClient(adi.config).UpdateOne(adi)
}

// Unwrap unwraps the AppDictItem entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (adi *AppDictItem) Unwrap() *AppDictItem {
	_tx, ok := adi.config.driver.(*txDriver)
	if !ok {
		panic("ent: AppDictItem is not a transactional entity")
	}
	adi.config.driver = _tx.drv
	return adi
}

// String implements the fmt.Stringer.
func (adi *AppDictItem) String() string {
	var builder strings.Builder
	builder.WriteString("AppDictItem(")
	builder.WriteString(fmt.Sprintf("id=%v, ", adi.ID))
	builder.WriteString("org_id=")
	builder.WriteString(fmt.Sprintf("%v", adi.OrgID))
	builder.WriteString(", ")
	builder.WriteString("ref_code=")
	builder.WriteString(adi.RefCode)
	builder.WriteString(", ")
	builder.WriteString("code=")
	builder.WriteString(adi.Code)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(adi.Name)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", adi.Status))
	builder.WriteByte(')')
	return builder.String()
}

// AppDictItems is a parsable slice of AppDictItem.
type AppDictItems []*AppDictItem
