// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/woocoos/msgcenter/ent/msgevent"
	"github.com/woocoos/msgcenter/ent/msgtemplate"
	"github.com/woocoos/msgcenter/ent/msgtype"
	"github.com/woocoos/msgcenter/ent/predicate"

	"github.com/woocoos/msgcenter/ent/internal"
)

// MsgEventQuery is the builder for querying MsgEvent entities.
type MsgEventQuery struct {
	config
	ctx                       *QueryContext
	order                     []msgevent.OrderOption
	inters                    []Interceptor
	predicates                []predicate.MsgEvent
	withMsgType               *MsgTypeQuery
	withCustomerTemplate      *MsgTemplateQuery
	modifiers                 []func(*sql.Selector)
	loadTotal                 []func(context.Context, []*MsgEvent) error
	withNamedCustomerTemplate map[string]*MsgTemplateQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MsgEventQuery builder.
func (_q *MsgEventQuery) Where(ps ...predicate.MsgEvent) *MsgEventQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *MsgEventQuery) Limit(limit int) *MsgEventQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *MsgEventQuery) Offset(offset int) *MsgEventQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *MsgEventQuery) Unique(unique bool) *MsgEventQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *MsgEventQuery) Order(o ...msgevent.OrderOption) *MsgEventQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryMsgType chains the current query on the "msg_type" edge.
func (_q *MsgEventQuery) QueryMsgType() *MsgTypeQuery {
	query := (&MsgTypeClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(msgevent.Table, msgevent.FieldID, selector),
			sqlgraph.To(msgtype.Table, msgtype.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, msgevent.MsgTypeTable, msgevent.MsgTypeColumn),
		)
		schemaConfig := _q.schemaConfig
		step.To.Schema = schemaConfig.MsgType
		step.Edge.Schema = schemaConfig.MsgEvent
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCustomerTemplate chains the current query on the "customer_template" edge.
func (_q *MsgEventQuery) QueryCustomerTemplate() *MsgTemplateQuery {
	query := (&MsgTemplateClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(msgevent.Table, msgevent.FieldID, selector),
			sqlgraph.To(msgtemplate.Table, msgtemplate.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, msgevent.CustomerTemplateTable, msgevent.CustomerTemplateColumn),
		)
		schemaConfig := _q.schemaConfig
		step.To.Schema = schemaConfig.MsgTemplate
		step.Edge.Schema = schemaConfig.MsgTemplate
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first MsgEvent entity from the query.
// Returns a *NotFoundError when no MsgEvent was found.
func (_q *MsgEventQuery) First(ctx context.Context) (*MsgEvent, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{msgevent.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *MsgEventQuery) FirstX(ctx context.Context) *MsgEvent {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MsgEvent ID from the query.
// Returns a *NotFoundError when no MsgEvent ID was found.
func (_q *MsgEventQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{msgevent.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *MsgEventQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MsgEvent entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MsgEvent entity is found.
// Returns a *NotFoundError when no MsgEvent entities are found.
func (_q *MsgEventQuery) Only(ctx context.Context) (*MsgEvent, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{msgevent.Label}
	default:
		return nil, &NotSingularError{msgevent.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *MsgEventQuery) OnlyX(ctx context.Context) *MsgEvent {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MsgEvent ID in the query.
// Returns a *NotSingularError when more than one MsgEvent ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *MsgEventQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{msgevent.Label}
	default:
		err = &NotSingularError{msgevent.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *MsgEventQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MsgEvents.
func (_q *MsgEventQuery) All(ctx context.Context) ([]*MsgEvent, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*MsgEvent, *MsgEventQuery]()
	return withInterceptors[[]*MsgEvent](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *MsgEventQuery) AllX(ctx context.Context) []*MsgEvent {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MsgEvent IDs.
func (_q *MsgEventQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(msgevent.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *MsgEventQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *MsgEventQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*MsgEventQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *MsgEventQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *MsgEventQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *MsgEventQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MsgEventQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *MsgEventQuery) Clone() *MsgEventQuery {
	if _q == nil {
		return nil
	}
	return &MsgEventQuery{
		config:               _q.config,
		ctx:                  _q.ctx.Clone(),
		order:                append([]msgevent.OrderOption{}, _q.order...),
		inters:               append([]Interceptor{}, _q.inters...),
		predicates:           append([]predicate.MsgEvent{}, _q.predicates...),
		withMsgType:          _q.withMsgType.Clone(),
		withCustomerTemplate: _q.withCustomerTemplate.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithMsgType tells the query-builder to eager-load the nodes that are connected to
// the "msg_type" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *MsgEventQuery) WithMsgType(opts ...func(*MsgTypeQuery)) *MsgEventQuery {
	query := (&MsgTypeClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withMsgType = query
	return _q
}

// WithCustomerTemplate tells the query-builder to eager-load the nodes that are connected to
// the "customer_template" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *MsgEventQuery) WithCustomerTemplate(opts ...func(*MsgTemplateQuery)) *MsgEventQuery {
	query := (&MsgTemplateClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCustomerTemplate = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedBy int `json:"created_by,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MsgEvent.Query().
//		GroupBy(msgevent.FieldCreatedBy).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *MsgEventQuery) GroupBy(field string, fields ...string) *MsgEventGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &MsgEventGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = msgevent.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedBy int `json:"created_by,omitempty"`
//	}
//
//	client.MsgEvent.Query().
//		Select(msgevent.FieldCreatedBy).
//		Scan(ctx, &v)
func (_q *MsgEventQuery) Select(fields ...string) *MsgEventSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &MsgEventSelect{MsgEventQuery: _q}
	sbuild.label = msgevent.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a MsgEventSelect configured with the given aggregations.
func (_q *MsgEventQuery) Aggregate(fns ...AggregateFunc) *MsgEventSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *MsgEventQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !msgevent.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *MsgEventQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*MsgEvent, error) {
	var (
		nodes       = []*MsgEvent{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withMsgType != nil,
			_q.withCustomerTemplate != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*MsgEvent).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &MsgEvent{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	_spec.Node.Schema = _q.schemaConfig.MsgEvent
	ctx = internal.NewSchemaConfigContext(ctx, _q.schemaConfig)
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withMsgType; query != nil {
		if err := _q.loadMsgType(ctx, query, nodes, nil,
			func(n *MsgEvent, e *MsgType) { n.Edges.MsgType = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withCustomerTemplate; query != nil {
		if err := _q.loadCustomerTemplate(ctx, query, nodes,
			func(n *MsgEvent) { n.Edges.CustomerTemplate = []*MsgTemplate{} },
			func(n *MsgEvent, e *MsgTemplate) { n.Edges.CustomerTemplate = append(n.Edges.CustomerTemplate, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range _q.withNamedCustomerTemplate {
		if err := _q.loadCustomerTemplate(ctx, query, nodes,
			func(n *MsgEvent) { n.appendNamedCustomerTemplate(name) },
			func(n *MsgEvent, e *MsgTemplate) { n.appendNamedCustomerTemplate(name, e) }); err != nil {
			return nil, err
		}
	}
	for i := range _q.loadTotal {
		if err := _q.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *MsgEventQuery) loadMsgType(ctx context.Context, query *MsgTypeQuery, nodes []*MsgEvent, init func(*MsgEvent), assign func(*MsgEvent, *MsgType)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*MsgEvent)
	for i := range nodes {
		fk := nodes[i].MsgTypeID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(msgtype.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "msg_type_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *MsgEventQuery) loadCustomerTemplate(ctx context.Context, query *MsgTemplateQuery, nodes []*MsgEvent, init func(*MsgEvent), assign func(*MsgEvent, *MsgTemplate)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*MsgEvent)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(msgtemplate.FieldMsgEventID)
	}
	query.Where(predicate.MsgTemplate(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(msgevent.CustomerTemplateColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.MsgEventID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "msg_event_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *MsgEventQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Schema = _q.schemaConfig.MsgEvent
	ctx = internal.NewSchemaConfigContext(ctx, _q.schemaConfig)
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *MsgEventQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(msgevent.Table, msgevent.Columns, sqlgraph.NewFieldSpec(msgevent.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, msgevent.FieldID)
		for i := range fields {
			if fields[i] != msgevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withMsgType != nil {
			_spec.Node.AddColumnOnce(msgevent.FieldMsgTypeID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *MsgEventQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(msgevent.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = msgevent.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	t1.Schema(_q.schemaConfig.MsgEvent)
	ctx = internal.NewSchemaConfigContext(ctx, _q.schemaConfig)
	selector.WithContext(ctx)
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WithNamedCustomerTemplate tells the query-builder to eager-load the nodes that are connected to the "customer_template"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (_q *MsgEventQuery) WithNamedCustomerTemplate(name string, opts ...func(*MsgTemplateQuery)) *MsgEventQuery {
	query := (&MsgTemplateClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if _q.withNamedCustomerTemplate == nil {
		_q.withNamedCustomerTemplate = make(map[string]*MsgTemplateQuery)
	}
	_q.withNamedCustomerTemplate[name] = query
	return _q
}

// MsgEventGroupBy is the group-by builder for MsgEvent entities.
type MsgEventGroupBy struct {
	selector
	build *MsgEventQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *MsgEventGroupBy) Aggregate(fns ...AggregateFunc) *MsgEventGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *MsgEventGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MsgEventQuery, *MsgEventGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *MsgEventGroupBy) sqlScan(ctx context.Context, root *MsgEventQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// MsgEventSelect is the builder for selecting fields of MsgEvent entities.
type MsgEventSelect struct {
	*MsgEventQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *MsgEventSelect) Aggregate(fns ...AggregateFunc) *MsgEventSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *MsgEventSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MsgEventQuery, *MsgEventSelect](ctx, _s.MsgEventQuery, _s, _s.inters, v)
}

func (_s *MsgEventSelect) sqlScan(ctx context.Context, root *MsgEventQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
