// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/woocoos/msgcenter/ent/msgtemplate"
	"github.com/woocoos/msgcenter/ent/predicate"
)

// MsgTemplateDelete is the builder for deleting a MsgTemplate entity.
type MsgTemplateDelete struct {
	config
	hooks    []Hook
	mutation *MsgTemplateMutation
}

// Where appends a list predicates to the MsgTemplateDelete builder.
func (mtd *MsgTemplateDelete) Where(ps ...predicate.MsgTemplate) *MsgTemplateDelete {
	mtd.mutation.Where(ps...)
	return mtd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (mtd *MsgTemplateDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, mtd.sqlExec, mtd.mutation, mtd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (mtd *MsgTemplateDelete) ExecX(ctx context.Context) int {
	n, err := mtd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (mtd *MsgTemplateDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(msgtemplate.Table, sqlgraph.NewFieldSpec(msgtemplate.FieldID, field.TypeInt))
	if ps := mtd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, mtd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	mtd.mutation.done = true
	return affected, err
}

// MsgTemplateDeleteOne is the builder for deleting a single MsgTemplate entity.
type MsgTemplateDeleteOne struct {
	mtd *MsgTemplateDelete
}

// Where appends a list predicates to the MsgTemplateDelete builder.
func (mtdo *MsgTemplateDeleteOne) Where(ps ...predicate.MsgTemplate) *MsgTemplateDeleteOne {
	mtdo.mtd.mutation.Where(ps...)
	return mtdo
}

// Exec executes the deletion query.
func (mtdo *MsgTemplateDeleteOne) Exec(ctx context.Context) error {
	n, err := mtdo.mtd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{msgtemplate.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (mtdo *MsgTemplateDeleteOne) ExecX(ctx context.Context) {
	if err := mtdo.Exec(ctx); err != nil {
		panic(err)
	}
}
