// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/woocoos/msgcenter/ent/msgevent"
	"github.com/woocoos/msgcenter/ent/msgtemplate"
	"github.com/woocoos/msgcenter/ent/predicate"

	"github.com/woocoos/msgcenter/ent/internal"
)

// MsgTemplateQuery is the builder for querying MsgTemplate entities.
type MsgTemplateQuery struct {
	config
	ctx        *QueryContext
	order      []msgtemplate.OrderOption
	inters     []Interceptor
	predicates []predicate.MsgTemplate
	withEvent  *MsgEventQuery
	modifiers  []func(*sql.Selector)
	loadTotal  []func(context.Context, []*MsgTemplate) error
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MsgTemplateQuery builder.
func (_q *MsgTemplateQuery) Where(ps ...predicate.MsgTemplate) *MsgTemplateQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *MsgTemplateQuery) Limit(limit int) *MsgTemplateQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *MsgTemplateQuery) Offset(offset int) *MsgTemplateQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *MsgTemplateQuery) Unique(unique bool) *MsgTemplateQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *MsgTemplateQuery) Order(o ...msgtemplate.OrderOption) *MsgTemplateQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryEvent chains the current query on the "event" edge.
func (_q *MsgTemplateQuery) QueryEvent() *MsgEventQuery {
	query := (&MsgEventClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(msgtemplate.Table, msgtemplate.FieldID, selector),
			sqlgraph.To(msgevent.Table, msgevent.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, msgtemplate.EventTable, msgtemplate.EventColumn),
		)
		schemaConfig := _q.schemaConfig
		step.To.Schema = schemaConfig.MsgEvent
		step.Edge.Schema = schemaConfig.MsgTemplate
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first MsgTemplate entity from the query.
// Returns a *NotFoundError when no MsgTemplate was found.
func (_q *MsgTemplateQuery) First(ctx context.Context) (*MsgTemplate, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{msgtemplate.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *MsgTemplateQuery) FirstX(ctx context.Context) *MsgTemplate {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MsgTemplate ID from the query.
// Returns a *NotFoundError when no MsgTemplate ID was found.
func (_q *MsgTemplateQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{msgtemplate.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *MsgTemplateQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MsgTemplate entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MsgTemplate entity is found.
// Returns a *NotFoundError when no MsgTemplate entities are found.
func (_q *MsgTemplateQuery) Only(ctx context.Context) (*MsgTemplate, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{msgtemplate.Label}
	default:
		return nil, &NotSingularError{msgtemplate.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *MsgTemplateQuery) OnlyX(ctx context.Context) *MsgTemplate {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MsgTemplate ID in the query.
// Returns a *NotSingularError when more than one MsgTemplate ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *MsgTemplateQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{msgtemplate.Label}
	default:
		err = &NotSingularError{msgtemplate.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *MsgTemplateQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MsgTemplates.
func (_q *MsgTemplateQuery) All(ctx context.Context) ([]*MsgTemplate, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*MsgTemplate, *MsgTemplateQuery]()
	return withInterceptors[[]*MsgTemplate](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *MsgTemplateQuery) AllX(ctx context.Context) []*MsgTemplate {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MsgTemplate IDs.
func (_q *MsgTemplateQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(msgtemplate.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *MsgTemplateQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *MsgTemplateQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*MsgTemplateQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *MsgTemplateQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *MsgTemplateQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *MsgTemplateQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MsgTemplateQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *MsgTemplateQuery) Clone() *MsgTemplateQuery {
	if _q == nil {
		return nil
	}
	return &MsgTemplateQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]msgtemplate.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.MsgTemplate{}, _q.predicates...),
		withEvent:  _q.withEvent.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithEvent tells the query-builder to eager-load the nodes that are connected to
// the "event" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *MsgTemplateQuery) WithEvent(opts ...func(*MsgEventQuery)) *MsgTemplateQuery {
	query := (&MsgEventClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withEvent = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedBy int `json:"created_by,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MsgTemplate.Query().
//		GroupBy(msgtemplate.FieldCreatedBy).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *MsgTemplateQuery) GroupBy(field string, fields ...string) *MsgTemplateGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &MsgTemplateGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = msgtemplate.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedBy int `json:"created_by,omitempty"`
//	}
//
//	client.MsgTemplate.Query().
//		Select(msgtemplate.FieldCreatedBy).
//		Scan(ctx, &v)
func (_q *MsgTemplateQuery) Select(fields ...string) *MsgTemplateSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &MsgTemplateSelect{MsgTemplateQuery: _q}
	sbuild.label = msgtemplate.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a MsgTemplateSelect configured with the given aggregations.
func (_q *MsgTemplateQuery) Aggregate(fns ...AggregateFunc) *MsgTemplateSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *MsgTemplateQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !msgtemplate.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *MsgTemplateQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*MsgTemplate, error) {
	var (
		nodes       = []*MsgTemplate{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withEvent != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*MsgTemplate).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &MsgTemplate{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	_spec.Node.Schema = _q.schemaConfig.MsgTemplate
	ctx = internal.NewSchemaConfigContext(ctx, _q.schemaConfig)
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withEvent; query != nil {
		if err := _q.loadEvent(ctx, query, nodes, nil,
			func(n *MsgTemplate, e *MsgEvent) { n.Edges.Event = e }); err != nil {
			return nil, err
		}
	}
	for i := range _q.loadTotal {
		if err := _q.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *MsgTemplateQuery) loadEvent(ctx context.Context, query *MsgEventQuery, nodes []*MsgTemplate, init func(*MsgTemplate), assign func(*MsgTemplate, *MsgEvent)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*MsgTemplate)
	for i := range nodes {
		fk := nodes[i].MsgEventID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(msgevent.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "msg_event_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *MsgTemplateQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Schema = _q.schemaConfig.MsgTemplate
	ctx = internal.NewSchemaConfigContext(ctx, _q.schemaConfig)
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *MsgTemplateQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(msgtemplate.Table, msgtemplate.Columns, sqlgraph.NewFieldSpec(msgtemplate.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, msgtemplate.FieldID)
		for i := range fields {
			if fields[i] != msgtemplate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withEvent != nil {
			_spec.Node.AddColumnOnce(msgtemplate.FieldMsgEventID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *MsgTemplateQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(msgtemplate.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = msgtemplate.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	t1.Schema(_q.schemaConfig.MsgTemplate)
	ctx = internal.NewSchemaConfigContext(ctx, _q.schemaConfig)
	selector.WithContext(ctx)
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MsgTemplateGroupBy is the group-by builder for MsgTemplate entities.
type MsgTemplateGroupBy struct {
	selector
	build *MsgTemplateQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *MsgTemplateGroupBy) Aggregate(fns ...AggregateFunc) *MsgTemplateGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *MsgTemplateGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MsgTemplateQuery, *MsgTemplateGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *MsgTemplateGroupBy) sqlScan(ctx context.Context, root *MsgTemplateQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// MsgTemplateSelect is the builder for selecting fields of MsgTemplate entities.
type MsgTemplateSelect struct {
	*MsgTemplateQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *MsgTemplateSelect) Aggregate(fns ...AggregateFunc) *MsgTemplateSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *MsgTemplateSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MsgTemplateQuery, *MsgTemplateSelect](ctx, _s.MsgTemplateQuery, _s, _s.inters, v)
}

func (_s *MsgTemplateSelect) sqlScan(ctx context.Context, root *MsgTemplateQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
