// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/woocoos/msgcenter/ent/msgalert"
	"github.com/woocoos/msgcenter/ent/nlog"
	"github.com/woocoos/msgcenter/ent/nlogalert"
	"github.com/woocoos/msgcenter/ent/predicate"

	"github.com/woocoos/msgcenter/ent/internal"
)

// NlogAlertUpdate is the builder for updating NlogAlert entities.
type NlogAlertUpdate struct {
	config
	hooks    []Hook
	mutation *NlogAlertMutation
}

// Where appends a list predicates to the NlogAlertUpdate builder.
func (_u *NlogAlertUpdate) Where(ps ...predicate.NlogAlert) *NlogAlertUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetNlogID sets the "nlog_id" field.
func (_u *NlogAlertUpdate) SetNlogID(v int) *NlogAlertUpdate {
	_u.mutation.SetNlogID(v)
	return _u
}

// SetNillableNlogID sets the "nlog_id" field if the given value is not nil.
func (_u *NlogAlertUpdate) SetNillableNlogID(v *int) *NlogAlertUpdate {
	if v != nil {
		_u.SetNlogID(*v)
	}
	return _u
}

// SetAlertID sets the "alert_id" field.
func (_u *NlogAlertUpdate) SetAlertID(v int) *NlogAlertUpdate {
	_u.mutation.SetAlertID(v)
	return _u
}

// SetNillableAlertID sets the "alert_id" field if the given value is not nil.
func (_u *NlogAlertUpdate) SetNillableAlertID(v *int) *NlogAlertUpdate {
	if v != nil {
		_u.SetAlertID(*v)
	}
	return _u
}

// SetNlog sets the "nlog" edge to the Nlog entity.
func (_u *NlogAlertUpdate) SetNlog(v *Nlog) *NlogAlertUpdate {
	return _u.SetNlogID(v.ID)
}

// SetAlert sets the "alert" edge to the MsgAlert entity.
func (_u *NlogAlertUpdate) SetAlert(v *MsgAlert) *NlogAlertUpdate {
	return _u.SetAlertID(v.ID)
}

// Mutation returns the NlogAlertMutation object of the builder.
func (_u *NlogAlertUpdate) Mutation() *NlogAlertMutation {
	return _u.mutation
}

// ClearNlog clears the "nlog" edge to the Nlog entity.
func (_u *NlogAlertUpdate) ClearNlog() *NlogAlertUpdate {
	_u.mutation.ClearNlog()
	return _u
}

// ClearAlert clears the "alert" edge to the MsgAlert entity.
func (_u *NlogAlertUpdate) ClearAlert() *NlogAlertUpdate {
	_u.mutation.ClearAlert()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NlogAlertUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NlogAlertUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NlogAlertUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NlogAlertUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NlogAlertUpdate) check() error {
	if _u.mutation.NlogCleared() && len(_u.mutation.NlogIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "NlogAlert.nlog"`)
	}
	if _u.mutation.AlertCleared() && len(_u.mutation.AlertIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "NlogAlert.alert"`)
	}
	return nil
}

func (_u *NlogAlertUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(nlogalert.Table, nlogalert.Columns, sqlgraph.NewFieldSpec(nlogalert.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.NlogCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   nlogalert.NlogTable,
			Columns: []string{nlogalert.NlogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nlog.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.NlogAlert
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NlogIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   nlogalert.NlogTable,
			Columns: []string{nlogalert.NlogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nlog.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.NlogAlert
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AlertCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   nlogalert.AlertTable,
			Columns: []string{nlogalert.AlertColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(msgalert.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.NlogAlert
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AlertIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   nlogalert.AlertTable,
			Columns: []string{nlogalert.AlertColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(msgalert.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.NlogAlert
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.NlogAlert
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{nlogalert.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NlogAlertUpdateOne is the builder for updating a single NlogAlert entity.
type NlogAlertUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NlogAlertMutation
}

// SetNlogID sets the "nlog_id" field.
func (_u *NlogAlertUpdateOne) SetNlogID(v int) *NlogAlertUpdateOne {
	_u.mutation.SetNlogID(v)
	return _u
}

// SetNillableNlogID sets the "nlog_id" field if the given value is not nil.
func (_u *NlogAlertUpdateOne) SetNillableNlogID(v *int) *NlogAlertUpdateOne {
	if v != nil {
		_u.SetNlogID(*v)
	}
	return _u
}

// SetAlertID sets the "alert_id" field.
func (_u *NlogAlertUpdateOne) SetAlertID(v int) *NlogAlertUpdateOne {
	_u.mutation.SetAlertID(v)
	return _u
}

// SetNillableAlertID sets the "alert_id" field if the given value is not nil.
func (_u *NlogAlertUpdateOne) SetNillableAlertID(v *int) *NlogAlertUpdateOne {
	if v != nil {
		_u.SetAlertID(*v)
	}
	return _u
}

// SetNlog sets the "nlog" edge to the Nlog entity.
func (_u *NlogAlertUpdateOne) SetNlog(v *Nlog) *NlogAlertUpdateOne {
	return _u.SetNlogID(v.ID)
}

// SetAlert sets the "alert" edge to the MsgAlert entity.
func (_u *NlogAlertUpdateOne) SetAlert(v *MsgAlert) *NlogAlertUpdateOne {
	return _u.SetAlertID(v.ID)
}

// Mutation returns the NlogAlertMutation object of the builder.
func (_u *NlogAlertUpdateOne) Mutation() *NlogAlertMutation {
	return _u.mutation
}

// ClearNlog clears the "nlog" edge to the Nlog entity.
func (_u *NlogAlertUpdateOne) ClearNlog() *NlogAlertUpdateOne {
	_u.mutation.ClearNlog()
	return _u
}

// ClearAlert clears the "alert" edge to the MsgAlert entity.
func (_u *NlogAlertUpdateOne) ClearAlert() *NlogAlertUpdateOne {
	_u.mutation.ClearAlert()
	return _u
}

// Where appends a list predicates to the NlogAlertUpdate builder.
func (_u *NlogAlertUpdateOne) Where(ps ...predicate.NlogAlert) *NlogAlertUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NlogAlertUpdateOne) Select(field string, fields ...string) *NlogAlertUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated NlogAlert entity.
func (_u *NlogAlertUpdateOne) Save(ctx context.Context) (*NlogAlert, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NlogAlertUpdateOne) SaveX(ctx context.Context) *NlogAlert {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NlogAlertUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NlogAlertUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NlogAlertUpdateOne) check() error {
	if _u.mutation.NlogCleared() && len(_u.mutation.NlogIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "NlogAlert.nlog"`)
	}
	if _u.mutation.AlertCleared() && len(_u.mutation.AlertIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "NlogAlert.alert"`)
	}
	return nil
}

func (_u *NlogAlertUpdateOne) sqlSave(ctx context.Context) (_node *NlogAlert, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(nlogalert.Table, nlogalert.Columns, sqlgraph.NewFieldSpec(nlogalert.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "NlogAlert.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, nlogalert.FieldID)
		for _, f := range fields {
			if !nlogalert.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != nlogalert.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.NlogCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   nlogalert.NlogTable,
			Columns: []string{nlogalert.NlogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nlog.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.NlogAlert
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NlogIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   nlogalert.NlogTable,
			Columns: []string{nlogalert.NlogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nlog.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.NlogAlert
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AlertCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   nlogalert.AlertTable,
			Columns: []string{nlogalert.AlertColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(msgalert.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.NlogAlert
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AlertIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   nlogalert.AlertTable,
			Columns: []string{nlogalert.AlertColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(msgalert.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.NlogAlert
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.NlogAlert
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	_node = &NlogAlert{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{nlogalert.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
