// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/woocoos/msgcenter/ent/msgalert"
	"github.com/woocoos/msgcenter/ent/nlog"
	"github.com/woocoos/msgcenter/ent/nlogalert"
)

// NlogAlertCreate is the builder for creating a NlogAlert entity.
type NlogAlertCreate struct {
	config
	mutation *NlogAlertMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetNlogID sets the "nlog_id" field.
func (_c *NlogAlertCreate) SetNlogID(v int) *NlogAlertCreate {
	_c.mutation.SetNlogID(v)
	return _c
}

// SetAlertID sets the "alert_id" field.
func (_c *NlogAlertCreate) SetAlertID(v int) *NlogAlertCreate {
	_c.mutation.SetAlertID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *NlogAlertCreate) SetCreatedAt(v time.Time) *NlogAlertCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *NlogAlertCreate) SetNillableCreatedAt(v *time.Time) *NlogAlertCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetNlog sets the "nlog" edge to the Nlog entity.
func (_c *NlogAlertCreate) SetNlog(v *Nlog) *NlogAlertCreate {
	return _c.SetNlogID(v.ID)
}

// SetAlert sets the "alert" edge to the MsgAlert entity.
func (_c *NlogAlertCreate) SetAlert(v *MsgAlert) *NlogAlertCreate {
	return _c.SetAlertID(v.ID)
}

// Mutation returns the NlogAlertMutation object of the builder.
func (_c *NlogAlertCreate) Mutation() *NlogAlertMutation {
	return _c.mutation
}

// Save creates the NlogAlert in the database.
func (_c *NlogAlertCreate) Save(ctx context.Context) (*NlogAlert, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NlogAlertCreate) SaveX(ctx context.Context) *NlogAlert {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NlogAlertCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NlogAlertCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *NlogAlertCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := nlogalert.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *NlogAlertCreate) check() error {
	if _, ok := _c.mutation.NlogID(); !ok {
		return &ValidationError{Name: "nlog_id", err: errors.New(`ent: missing required field "NlogAlert.nlog_id"`)}
	}
	if _, ok := _c.mutation.AlertID(); !ok {
		return &ValidationError{Name: "alert_id", err: errors.New(`ent: missing required field "NlogAlert.alert_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "NlogAlert.created_at"`)}
	}
	if len(_c.mutation.NlogIDs()) == 0 {
		return &ValidationError{Name: "nlog", err: errors.New(`ent: missing required edge "NlogAlert.nlog"`)}
	}
	if len(_c.mutation.AlertIDs()) == 0 {
		return &ValidationError{Name: "alert", err: errors.New(`ent: missing required edge "NlogAlert.alert"`)}
	}
	return nil
}

func (_c *NlogAlertCreate) sqlSave(ctx context.Context) (*NlogAlert, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NlogAlertCreate) createSpec() (*NlogAlert, *sqlgraph.CreateSpec) {
	var (
		_node = &NlogAlert{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(nlogalert.Table, sqlgraph.NewFieldSpec(nlogalert.FieldID, field.TypeInt))
	)
	_spec.Schema = _c.schemaConfig.NlogAlert
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(nlogalert.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.NlogIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   nlogalert.NlogTable,
			Columns: []string{nlogalert.NlogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nlog.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _c.schemaConfig.NlogAlert
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.NlogID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AlertIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   nlogalert.AlertTable,
			Columns: []string{nlogalert.AlertColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(msgalert.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _c.schemaConfig.NlogAlert
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AlertID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.NlogAlert.Create().
//		SetNlogID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NlogAlertUpsert) {
//			SetNlogID(v+v).
//		}).
//		Exec(ctx)
func (_c *NlogAlertCreate) OnConflict(opts ...sql.ConflictOption) *NlogAlertUpsertOne {
	_c.conflict = opts
	return &NlogAlertUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.NlogAlert.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *NlogAlertCreate) OnConflictColumns(columns ...string) *NlogAlertUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &NlogAlertUpsertOne{
		create: _c,
	}
}

type (
	// NlogAlertUpsertOne is the builder for "upsert"-ing
	//  one NlogAlert node.
	NlogAlertUpsertOne struct {
		create *NlogAlertCreate
	}

	// NlogAlertUpsert is the "OnConflict" setter.
	NlogAlertUpsert struct {
		*sql.UpdateSet
	}
)

// SetNlogID sets the "nlog_id" field.
func (u *NlogAlertUpsert) SetNlogID(v int) *NlogAlertUpsert {
	u.Set(nlogalert.FieldNlogID, v)
	return u
}

// UpdateNlogID sets the "nlog_id" field to the value that was provided on create.
func (u *NlogAlertUpsert) UpdateNlogID() *NlogAlertUpsert {
	u.SetExcluded(nlogalert.FieldNlogID)
	return u
}

// SetAlertID sets the "alert_id" field.
func (u *NlogAlertUpsert) SetAlertID(v int) *NlogAlertUpsert {
	u.Set(nlogalert.FieldAlertID, v)
	return u
}

// UpdateAlertID sets the "alert_id" field to the value that was provided on create.
func (u *NlogAlertUpsert) UpdateAlertID() *NlogAlertUpsert {
	u.SetExcluded(nlogalert.FieldAlertID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.NlogAlert.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *NlogAlertUpsertOne) UpdateNewValues() *NlogAlertUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(nlogalert.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.NlogAlert.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *NlogAlertUpsertOne) Ignore() *NlogAlertUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NlogAlertUpsertOne) DoNothing() *NlogAlertUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NlogAlertCreate.OnConflict
// documentation for more info.
func (u *NlogAlertUpsertOne) Update(set func(*NlogAlertUpsert)) *NlogAlertUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NlogAlertUpsert{UpdateSet: update})
	}))
	return u
}

// SetNlogID sets the "nlog_id" field.
func (u *NlogAlertUpsertOne) SetNlogID(v int) *NlogAlertUpsertOne {
	return u.Update(func(s *NlogAlertUpsert) {
		s.SetNlogID(v)
	})
}

// UpdateNlogID sets the "nlog_id" field to the value that was provided on create.
func (u *NlogAlertUpsertOne) UpdateNlogID() *NlogAlertUpsertOne {
	return u.Update(func(s *NlogAlertUpsert) {
		s.UpdateNlogID()
	})
}

// SetAlertID sets the "alert_id" field.
func (u *NlogAlertUpsertOne) SetAlertID(v int) *NlogAlertUpsertOne {
	return u.Update(func(s *NlogAlertUpsert) {
		s.SetAlertID(v)
	})
}

// UpdateAlertID sets the "alert_id" field to the value that was provided on create.
func (u *NlogAlertUpsertOne) UpdateAlertID() *NlogAlertUpsertOne {
	return u.Update(func(s *NlogAlertUpsert) {
		s.UpdateAlertID()
	})
}

// Exec executes the query.
func (u *NlogAlertUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NlogAlertCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NlogAlertUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *NlogAlertUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *NlogAlertUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// NlogAlertCreateBulk is the builder for creating many NlogAlert entities in bulk.
type NlogAlertCreateBulk struct {
	config
	err      error
	builders []*NlogAlertCreate
	conflict []sql.ConflictOption
}

// Save creates the NlogAlert entities in the database.
func (_c *NlogAlertCreateBulk) Save(ctx context.Context) ([]*NlogAlert, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*NlogAlert, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NlogAlertMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NlogAlertCreateBulk) SaveX(ctx context.Context) []*NlogAlert {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NlogAlertCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NlogAlertCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.NlogAlert.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NlogAlertUpsert) {
//			SetNlogID(v+v).
//		}).
//		Exec(ctx)
func (_c *NlogAlertCreateBulk) OnConflict(opts ...sql.ConflictOption) *NlogAlertUpsertBulk {
	_c.conflict = opts
	return &NlogAlertUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.NlogAlert.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *NlogAlertCreateBulk) OnConflictColumns(columns ...string) *NlogAlertUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &NlogAlertUpsertBulk{
		create: _c,
	}
}

// NlogAlertUpsertBulk is the builder for "upsert"-ing
// a bulk of NlogAlert nodes.
type NlogAlertUpsertBulk struct {
	create *NlogAlertCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.NlogAlert.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *NlogAlertUpsertBulk) UpdateNewValues() *NlogAlertUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(nlogalert.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.NlogAlert.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *NlogAlertUpsertBulk) Ignore() *NlogAlertUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NlogAlertUpsertBulk) DoNothing() *NlogAlertUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NlogAlertCreateBulk.OnConflict
// documentation for more info.
func (u *NlogAlertUpsertBulk) Update(set func(*NlogAlertUpsert)) *NlogAlertUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NlogAlertUpsert{UpdateSet: update})
	}))
	return u
}

// SetNlogID sets the "nlog_id" field.
func (u *NlogAlertUpsertBulk) SetNlogID(v int) *NlogAlertUpsertBulk {
	return u.Update(func(s *NlogAlertUpsert) {
		s.SetNlogID(v)
	})
}

// UpdateNlogID sets the "nlog_id" field to the value that was provided on create.
func (u *NlogAlertUpsertBulk) UpdateNlogID() *NlogAlertUpsertBulk {
	return u.Update(func(s *NlogAlertUpsert) {
		s.UpdateNlogID()
	})
}

// SetAlertID sets the "alert_id" field.
func (u *NlogAlertUpsertBulk) SetAlertID(v int) *NlogAlertUpsertBulk {
	return u.Update(func(s *NlogAlertUpsert) {
		s.SetAlertID(v)
	})
}

// UpdateAlertID sets the "alert_id" field to the value that was provided on create.
func (u *NlogAlertUpsertBulk) UpdateAlertID() *NlogAlertUpsertBulk {
	return u.Update(func(s *NlogAlertUpsert) {
		s.UpdateAlertID()
	})
}

// Exec executes the query.
func (u *NlogAlertUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the NlogAlertCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NlogAlertCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NlogAlertUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
