// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/woocoos/msgcenter/ent/msgalert"
	"github.com/woocoos/msgcenter/ent/nlog"
	"github.com/woocoos/msgcenter/ent/nlogalert"
	"github.com/woocoos/msgcenter/ent/predicate"

	"github.com/woocoos/msgcenter/ent/internal"
)

// NlogQuery is the builder for querying Nlog entities.
type NlogQuery struct {
	config
	ctx                *QueryContext
	order              []nlog.OrderOption
	inters             []Interceptor
	predicates         []predicate.Nlog
	withAlerts         *MsgAlertQuery
	withNlogAlert      *NlogAlertQuery
	modifiers          []func(*sql.Selector)
	loadTotal          []func(context.Context, []*Nlog) error
	withNamedAlerts    map[string]*MsgAlertQuery
	withNamedNlogAlert map[string]*NlogAlertQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the NlogQuery builder.
func (_q *NlogQuery) Where(ps ...predicate.Nlog) *NlogQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *NlogQuery) Limit(limit int) *NlogQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *NlogQuery) Offset(offset int) *NlogQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *NlogQuery) Unique(unique bool) *NlogQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *NlogQuery) Order(o ...nlog.OrderOption) *NlogQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryAlerts chains the current query on the "alerts" edge.
func (_q *NlogQuery) QueryAlerts() *MsgAlertQuery {
	query := (&MsgAlertClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(nlog.Table, nlog.FieldID, selector),
			sqlgraph.To(msgalert.Table, msgalert.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, nlog.AlertsTable, nlog.AlertsPrimaryKey...),
		)
		schemaConfig := _q.schemaConfig
		step.To.Schema = schemaConfig.MsgAlert
		step.Edge.Schema = schemaConfig.NlogAlert
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryNlogAlert chains the current query on the "nlog_alert" edge.
func (_q *NlogQuery) QueryNlogAlert() *NlogAlertQuery {
	query := (&NlogAlertClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(nlog.Table, nlog.FieldID, selector),
			sqlgraph.To(nlogalert.Table, nlogalert.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, nlog.NlogAlertTable, nlog.NlogAlertColumn),
		)
		schemaConfig := _q.schemaConfig
		step.To.Schema = schemaConfig.NlogAlert
		step.Edge.Schema = schemaConfig.NlogAlert
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Nlog entity from the query.
// Returns a *NotFoundError when no Nlog was found.
func (_q *NlogQuery) First(ctx context.Context) (*Nlog, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{nlog.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *NlogQuery) FirstX(ctx context.Context) *Nlog {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Nlog ID from the query.
// Returns a *NotFoundError when no Nlog ID was found.
func (_q *NlogQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{nlog.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *NlogQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Nlog entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Nlog entity is found.
// Returns a *NotFoundError when no Nlog entities are found.
func (_q *NlogQuery) Only(ctx context.Context) (*Nlog, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{nlog.Label}
	default:
		return nil, &NotSingularError{nlog.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *NlogQuery) OnlyX(ctx context.Context) *Nlog {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Nlog ID in the query.
// Returns a *NotSingularError when more than one Nlog ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *NlogQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{nlog.Label}
	default:
		err = &NotSingularError{nlog.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *NlogQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Nlogs.
func (_q *NlogQuery) All(ctx context.Context) ([]*Nlog, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Nlog, *NlogQuery]()
	return withInterceptors[[]*Nlog](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *NlogQuery) AllX(ctx context.Context) []*Nlog {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Nlog IDs.
func (_q *NlogQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(nlog.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *NlogQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *NlogQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*NlogQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *NlogQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *NlogQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *NlogQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the NlogQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *NlogQuery) Clone() *NlogQuery {
	if _q == nil {
		return nil
	}
	return &NlogQuery{
		config:        _q.config,
		ctx:           _q.ctx.Clone(),
		order:         append([]nlog.OrderOption{}, _q.order...),
		inters:        append([]Interceptor{}, _q.inters...),
		predicates:    append([]predicate.Nlog{}, _q.predicates...),
		withAlerts:    _q.withAlerts.Clone(),
		withNlogAlert: _q.withNlogAlert.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithAlerts tells the query-builder to eager-load the nodes that are connected to
// the "alerts" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *NlogQuery) WithAlerts(opts ...func(*MsgAlertQuery)) *NlogQuery {
	query := (&MsgAlertClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAlerts = query
	return _q
}

// WithNlogAlert tells the query-builder to eager-load the nodes that are connected to
// the "nlog_alert" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *NlogQuery) WithNlogAlert(opts ...func(*NlogAlertQuery)) *NlogQuery {
	query := (&NlogAlertClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withNlogAlert = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TenantID int `json:"tenant_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Nlog.Query().
//		GroupBy(nlog.FieldTenantID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *NlogQuery) GroupBy(field string, fields ...string) *NlogGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &NlogGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = nlog.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TenantID int `json:"tenant_id,omitempty"`
//	}
//
//	client.Nlog.Query().
//		Select(nlog.FieldTenantID).
//		Scan(ctx, &v)
func (_q *NlogQuery) Select(fields ...string) *NlogSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &NlogSelect{NlogQuery: _q}
	sbuild.label = nlog.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a NlogSelect configured with the given aggregations.
func (_q *NlogQuery) Aggregate(fns ...AggregateFunc) *NlogSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *NlogQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !nlog.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *NlogQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Nlog, error) {
	var (
		nodes       = []*Nlog{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withAlerts != nil,
			_q.withNlogAlert != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Nlog).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Nlog{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	_spec.Node.Schema = _q.schemaConfig.Nlog
	ctx = internal.NewSchemaConfigContext(ctx, _q.schemaConfig)
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withAlerts; query != nil {
		if err := _q.loadAlerts(ctx, query, nodes,
			func(n *Nlog) { n.Edges.Alerts = []*MsgAlert{} },
			func(n *Nlog, e *MsgAlert) { n.Edges.Alerts = append(n.Edges.Alerts, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withNlogAlert; query != nil {
		if err := _q.loadNlogAlert(ctx, query, nodes,
			func(n *Nlog) { n.Edges.NlogAlert = []*NlogAlert{} },
			func(n *Nlog, e *NlogAlert) { n.Edges.NlogAlert = append(n.Edges.NlogAlert, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range _q.withNamedAlerts {
		if err := _q.loadAlerts(ctx, query, nodes,
			func(n *Nlog) { n.appendNamedAlerts(name) },
			func(n *Nlog, e *MsgAlert) { n.appendNamedAlerts(name, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range _q.withNamedNlogAlert {
		if err := _q.loadNlogAlert(ctx, query, nodes,
			func(n *Nlog) { n.appendNamedNlogAlert(name) },
			func(n *Nlog, e *NlogAlert) { n.appendNamedNlogAlert(name, e) }); err != nil {
			return nil, err
		}
	}
	for i := range _q.loadTotal {
		if err := _q.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *NlogQuery) loadAlerts(ctx context.Context, query *MsgAlertQuery, nodes []*Nlog, init func(*Nlog), assign func(*Nlog, *MsgAlert)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*Nlog)
	nids := make(map[int]map[*Nlog]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(nlog.AlertsTable)
		joinT.Schema(_q.schemaConfig.NlogAlert)
		s.Join(joinT).On(s.C(msgalert.FieldID), joinT.C(nlog.AlertsPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(nlog.AlertsPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(nlog.AlertsPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*Nlog]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*MsgAlert](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "alerts" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (_q *NlogQuery) loadNlogAlert(ctx context.Context, query *NlogAlertQuery, nodes []*Nlog, init func(*Nlog), assign func(*Nlog, *NlogAlert)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Nlog)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(nlogalert.FieldNlogID)
	}
	query.Where(predicate.NlogAlert(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(nlog.NlogAlertColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.NlogID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "nlog_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *NlogQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Schema = _q.schemaConfig.Nlog
	ctx = internal.NewSchemaConfigContext(ctx, _q.schemaConfig)
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *NlogQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(nlog.Table, nlog.Columns, sqlgraph.NewFieldSpec(nlog.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, nlog.FieldID)
		for i := range fields {
			if fields[i] != nlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *NlogQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(nlog.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = nlog.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	t1.Schema(_q.schemaConfig.Nlog)
	ctx = internal.NewSchemaConfigContext(ctx, _q.schemaConfig)
	selector.WithContext(ctx)
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WithNamedAlerts tells the query-builder to eager-load the nodes that are connected to the "alerts"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (_q *NlogQuery) WithNamedAlerts(name string, opts ...func(*MsgAlertQuery)) *NlogQuery {
	query := (&MsgAlertClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if _q.withNamedAlerts == nil {
		_q.withNamedAlerts = make(map[string]*MsgAlertQuery)
	}
	_q.withNamedAlerts[name] = query
	return _q
}

// WithNamedNlogAlert tells the query-builder to eager-load the nodes that are connected to the "nlog_alert"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (_q *NlogQuery) WithNamedNlogAlert(name string, opts ...func(*NlogAlertQuery)) *NlogQuery {
	query := (&NlogAlertClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if _q.withNamedNlogAlert == nil {
		_q.withNamedNlogAlert = make(map[string]*NlogAlertQuery)
	}
	_q.withNamedNlogAlert[name] = query
	return _q
}

// NlogGroupBy is the group-by builder for Nlog entities.
type NlogGroupBy struct {
	selector
	build *NlogQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *NlogGroupBy) Aggregate(fns ...AggregateFunc) *NlogGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *NlogGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*NlogQuery, *NlogGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *NlogGroupBy) sqlScan(ctx context.Context, root *NlogQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// NlogSelect is the builder for selecting fields of Nlog entities.
type NlogSelect struct {
	*NlogQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *NlogSelect) Aggregate(fns ...AggregateFunc) *NlogSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *NlogSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*NlogQuery, *NlogSelect](ctx, _s.NlogQuery, _s, _s.inters, v)
}

func (_s *NlogSelect) sqlScan(ctx context.Context, root *NlogQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
