// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/woocoos/msgcenter/ent/msgalert"
	"github.com/woocoos/msgcenter/ent/org"
	"github.com/woocoos/msgcenter/ent/predicate"

	"github.com/woocoos/msgcenter/ent/internal"
)

// OrgUpdate is the builder for updating Org entities.
type OrgUpdate struct {
	config
	hooks    []Hook
	mutation *OrgMutation
}

// Where appends a list predicates to the OrgUpdate builder.
func (_u *OrgUpdate) Where(ps ...predicate.Org) *OrgUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOwnerID sets the "owner_id" field.
func (_u *OrgUpdate) SetOwnerID(v int) *OrgUpdate {
	_u.mutation.ResetOwnerID()
	_u.mutation.SetOwnerID(v)
	return _u
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_u *OrgUpdate) SetNillableOwnerID(v *int) *OrgUpdate {
	if v != nil {
		_u.SetOwnerID(*v)
	}
	return _u
}

// AddOwnerID adds value to the "owner_id" field.
func (_u *OrgUpdate) AddOwnerID(v int) *OrgUpdate {
	_u.mutation.AddOwnerID(v)
	return _u
}

// ClearOwnerID clears the value of the "owner_id" field.
func (_u *OrgUpdate) ClearOwnerID() *OrgUpdate {
	_u.mutation.ClearOwnerID()
	return _u
}

// SetKind sets the "kind" field.
func (_u *OrgUpdate) SetKind(v string) *OrgUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *OrgUpdate) SetNillableKind(v *string) *OrgUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// ClearKind clears the value of the "kind" field.
func (_u *OrgUpdate) ClearKind() *OrgUpdate {
	_u.mutation.ClearKind()
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *OrgUpdate) SetParentID(v int) *OrgUpdate {
	_u.mutation.ResetParentID()
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *OrgUpdate) SetNillableParentID(v *int) *OrgUpdate {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// AddParentID adds value to the "parent_id" field.
func (_u *OrgUpdate) AddParentID(v int) *OrgUpdate {
	_u.mutation.AddParentID(v)
	return _u
}

// ClearParentID clears the value of the "parent_id" field.
func (_u *OrgUpdate) ClearParentID() *OrgUpdate {
	_u.mutation.ClearParentID()
	return _u
}

// SetPath sets the "path" field.
func (_u *OrgUpdate) SetPath(v string) *OrgUpdate {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *OrgUpdate) SetNillablePath(v *string) *OrgUpdate {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// ClearPath clears the value of the "path" field.
func (_u *OrgUpdate) ClearPath() *OrgUpdate {
	_u.mutation.ClearPath()
	return _u
}

// AddMsgAlertIDs adds the "msg_alerts" edge to the MsgAlert entity by IDs.
func (_u *OrgUpdate) AddMsgAlertIDs(ids ...int) *OrgUpdate {
	_u.mutation.AddMsgAlertIDs(ids...)
	return _u
}

// AddMsgAlerts adds the "msg_alerts" edges to the MsgAlert entity.
func (_u *OrgUpdate) AddMsgAlerts(v ...*MsgAlert) *OrgUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMsgAlertIDs(ids...)
}

// Mutation returns the OrgMutation object of the builder.
func (_u *OrgUpdate) Mutation() *OrgMutation {
	return _u.mutation
}

// ClearMsgAlerts clears all "msg_alerts" edges to the MsgAlert entity.
func (_u *OrgUpdate) ClearMsgAlerts() *OrgUpdate {
	_u.mutation.ClearMsgAlerts()
	return _u
}

// RemoveMsgAlertIDs removes the "msg_alerts" edge to MsgAlert entities by IDs.
func (_u *OrgUpdate) RemoveMsgAlertIDs(ids ...int) *OrgUpdate {
	_u.mutation.RemoveMsgAlertIDs(ids...)
	return _u
}

// RemoveMsgAlerts removes "msg_alerts" edges to MsgAlert entities.
func (_u *OrgUpdate) RemoveMsgAlerts(v ...*MsgAlert) *OrgUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMsgAlertIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OrgUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrgUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OrgUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrgUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *OrgUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(org.Table, org.Columns, sqlgraph.NewFieldSpec(org.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OwnerID(); ok {
		_spec.SetField(org.FieldOwnerID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOwnerID(); ok {
		_spec.AddField(org.FieldOwnerID, field.TypeInt, value)
	}
	if _u.mutation.OwnerIDCleared() {
		_spec.ClearField(org.FieldOwnerID, field.TypeInt)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(org.FieldKind, field.TypeString, value)
	}
	if _u.mutation.KindCleared() {
		_spec.ClearField(org.FieldKind, field.TypeString)
	}
	if value, ok := _u.mutation.ParentID(); ok {
		_spec.SetField(org.FieldParentID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedParentID(); ok {
		_spec.AddField(org.FieldParentID, field.TypeInt, value)
	}
	if _u.mutation.ParentIDCleared() {
		_spec.ClearField(org.FieldParentID, field.TypeInt)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(org.FieldPath, field.TypeString, value)
	}
	if _u.mutation.PathCleared() {
		_spec.ClearField(org.FieldPath, field.TypeString)
	}
	if _u.mutation.MsgAlertsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   org.MsgAlertsTable,
			Columns: []string{org.MsgAlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(msgalert.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.MsgAlert
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMsgAlertsIDs(); len(nodes) > 0 && !_u.mutation.MsgAlertsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   org.MsgAlertsTable,
			Columns: []string{org.MsgAlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(msgalert.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.MsgAlert
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MsgAlertsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   org.MsgAlertsTable,
			Columns: []string{org.MsgAlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(msgalert.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.MsgAlert
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.Org
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{org.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OrgUpdateOne is the builder for updating a single Org entity.
type OrgUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OrgMutation
}

// SetOwnerID sets the "owner_id" field.
func (_u *OrgUpdateOne) SetOwnerID(v int) *OrgUpdateOne {
	_u.mutation.ResetOwnerID()
	_u.mutation.SetOwnerID(v)
	return _u
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_u *OrgUpdateOne) SetNillableOwnerID(v *int) *OrgUpdateOne {
	if v != nil {
		_u.SetOwnerID(*v)
	}
	return _u
}

// AddOwnerID adds value to the "owner_id" field.
func (_u *OrgUpdateOne) AddOwnerID(v int) *OrgUpdateOne {
	_u.mutation.AddOwnerID(v)
	return _u
}

// ClearOwnerID clears the value of the "owner_id" field.
func (_u *OrgUpdateOne) ClearOwnerID() *OrgUpdateOne {
	_u.mutation.ClearOwnerID()
	return _u
}

// SetKind sets the "kind" field.
func (_u *OrgUpdateOne) SetKind(v string) *OrgUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *OrgUpdateOne) SetNillableKind(v *string) *OrgUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// ClearKind clears the value of the "kind" field.
func (_u *OrgUpdateOne) ClearKind() *OrgUpdateOne {
	_u.mutation.ClearKind()
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *OrgUpdateOne) SetParentID(v int) *OrgUpdateOne {
	_u.mutation.ResetParentID()
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *OrgUpdateOne) SetNillableParentID(v *int) *OrgUpdateOne {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// AddParentID adds value to the "parent_id" field.
func (_u *OrgUpdateOne) AddParentID(v int) *OrgUpdateOne {
	_u.mutation.AddParentID(v)
	return _u
}

// ClearParentID clears the value of the "parent_id" field.
func (_u *OrgUpdateOne) ClearParentID() *OrgUpdateOne {
	_u.mutation.ClearParentID()
	return _u
}

// SetPath sets the "path" field.
func (_u *OrgUpdateOne) SetPath(v string) *OrgUpdateOne {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *OrgUpdateOne) SetNillablePath(v *string) *OrgUpdateOne {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// ClearPath clears the value of the "path" field.
func (_u *OrgUpdateOne) ClearPath() *OrgUpdateOne {
	_u.mutation.ClearPath()
	return _u
}

// AddMsgAlertIDs adds the "msg_alerts" edge to the MsgAlert entity by IDs.
func (_u *OrgUpdateOne) AddMsgAlertIDs(ids ...int) *OrgUpdateOne {
	_u.mutation.AddMsgAlertIDs(ids...)
	return _u
}

// AddMsgAlerts adds the "msg_alerts" edges to the MsgAlert entity.
func (_u *OrgUpdateOne) AddMsgAlerts(v ...*MsgAlert) *OrgUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMsgAlertIDs(ids...)
}

// Mutation returns the OrgMutation object of the builder.
func (_u *OrgUpdateOne) Mutation() *OrgMutation {
	return _u.mutation
}

// ClearMsgAlerts clears all "msg_alerts" edges to the MsgAlert entity.
func (_u *OrgUpdateOne) ClearMsgAlerts() *OrgUpdateOne {
	_u.mutation.ClearMsgAlerts()
	return _u
}

// RemoveMsgAlertIDs removes the "msg_alerts" edge to MsgAlert entities by IDs.
func (_u *OrgUpdateOne) RemoveMsgAlertIDs(ids ...int) *OrgUpdateOne {
	_u.mutation.RemoveMsgAlertIDs(ids...)
	return _u
}

// RemoveMsgAlerts removes "msg_alerts" edges to MsgAlert entities.
func (_u *OrgUpdateOne) RemoveMsgAlerts(v ...*MsgAlert) *OrgUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMsgAlertIDs(ids...)
}

// Where appends a list predicates to the OrgUpdate builder.
func (_u *OrgUpdateOne) Where(ps ...predicate.Org) *OrgUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OrgUpdateOne) Select(field string, fields ...string) *OrgUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Org entity.
func (_u *OrgUpdateOne) Save(ctx context.Context) (*Org, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrgUpdateOne) SaveX(ctx context.Context) *Org {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OrgUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrgUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *OrgUpdateOne) sqlSave(ctx context.Context) (_node *Org, err error) {
	_spec := sqlgraph.NewUpdateSpec(org.Table, org.Columns, sqlgraph.NewFieldSpec(org.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Org.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, org.FieldID)
		for _, f := range fields {
			if !org.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != org.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OwnerID(); ok {
		_spec.SetField(org.FieldOwnerID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOwnerID(); ok {
		_spec.AddField(org.FieldOwnerID, field.TypeInt, value)
	}
	if _u.mutation.OwnerIDCleared() {
		_spec.ClearField(org.FieldOwnerID, field.TypeInt)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(org.FieldKind, field.TypeString, value)
	}
	if _u.mutation.KindCleared() {
		_spec.ClearField(org.FieldKind, field.TypeString)
	}
	if value, ok := _u.mutation.ParentID(); ok {
		_spec.SetField(org.FieldParentID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedParentID(); ok {
		_spec.AddField(org.FieldParentID, field.TypeInt, value)
	}
	if _u.mutation.ParentIDCleared() {
		_spec.ClearField(org.FieldParentID, field.TypeInt)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(org.FieldPath, field.TypeString, value)
	}
	if _u.mutation.PathCleared() {
		_spec.ClearField(org.FieldPath, field.TypeString)
	}
	if _u.mutation.MsgAlertsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   org.MsgAlertsTable,
			Columns: []string{org.MsgAlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(msgalert.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.MsgAlert
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMsgAlertsIDs(); len(nodes) > 0 && !_u.mutation.MsgAlertsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   org.MsgAlertsTable,
			Columns: []string{org.MsgAlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(msgalert.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.MsgAlert
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MsgAlertsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   org.MsgAlertsTable,
			Columns: []string{org.MsgAlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(msgalert.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.MsgAlert
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.Org
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	_node = &Org{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{org.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
