// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/woocoos/msgcenter/ent/msgalert"
	"github.com/woocoos/msgcenter/ent/org"
)

// OrgCreate is the builder for creating a Org entity.
type OrgCreate struct {
	config
	mutation *OrgMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetOwnerID sets the "owner_id" field.
func (_c *OrgCreate) SetOwnerID(v int) *OrgCreate {
	_c.mutation.SetOwnerID(v)
	return _c
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_c *OrgCreate) SetNillableOwnerID(v *int) *OrgCreate {
	if v != nil {
		_c.SetOwnerID(*v)
	}
	return _c
}

// SetKind sets the "kind" field.
func (_c *OrgCreate) SetKind(v string) *OrgCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_c *OrgCreate) SetNillableKind(v *string) *OrgCreate {
	if v != nil {
		_c.SetKind(*v)
	}
	return _c
}

// SetParentID sets the "parent_id" field.
func (_c *OrgCreate) SetParentID(v int) *OrgCreate {
	_c.mutation.SetParentID(v)
	return _c
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_c *OrgCreate) SetNillableParentID(v *int) *OrgCreate {
	if v != nil {
		_c.SetParentID(*v)
	}
	return _c
}

// SetPath sets the "path" field.
func (_c *OrgCreate) SetPath(v string) *OrgCreate {
	_c.mutation.SetPath(v)
	return _c
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_c *OrgCreate) SetNillablePath(v *string) *OrgCreate {
	if v != nil {
		_c.SetPath(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *OrgCreate) SetID(v int) *OrgCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddMsgAlertIDs adds the "msg_alerts" edge to the MsgAlert entity by IDs.
func (_c *OrgCreate) AddMsgAlertIDs(ids ...int) *OrgCreate {
	_c.mutation.AddMsgAlertIDs(ids...)
	return _c
}

// AddMsgAlerts adds the "msg_alerts" edges to the MsgAlert entity.
func (_c *OrgCreate) AddMsgAlerts(v ...*MsgAlert) *OrgCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMsgAlertIDs(ids...)
}

// Mutation returns the OrgMutation object of the builder.
func (_c *OrgCreate) Mutation() *OrgMutation {
	return _c.mutation
}

// Save creates the Org in the database.
func (_c *OrgCreate) Save(ctx context.Context) (*Org, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OrgCreate) SaveX(ctx context.Context) *Org {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrgCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrgCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OrgCreate) check() error {
	return nil
}

func (_c *OrgCreate) sqlSave(ctx context.Context) (*Org, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OrgCreate) createSpec() (*Org, *sqlgraph.CreateSpec) {
	var (
		_node = &Org{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(org.Table, sqlgraph.NewFieldSpec(org.FieldID, field.TypeInt))
	)
	_spec.Schema = _c.schemaConfig.Org
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.OwnerID(); ok {
		_spec.SetField(org.FieldOwnerID, field.TypeInt, value)
		_node.OwnerID = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(org.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.ParentID(); ok {
		_spec.SetField(org.FieldParentID, field.TypeInt, value)
		_node.ParentID = value
	}
	if value, ok := _c.mutation.Path(); ok {
		_spec.SetField(org.FieldPath, field.TypeString, value)
		_node.Path = value
	}
	if nodes := _c.mutation.MsgAlertsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   org.MsgAlertsTable,
			Columns: []string{org.MsgAlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(msgalert.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _c.schemaConfig.MsgAlert
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Org.Create().
//		SetOwnerID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OrgUpsert) {
//			SetOwnerID(v+v).
//		}).
//		Exec(ctx)
func (_c *OrgCreate) OnConflict(opts ...sql.ConflictOption) *OrgUpsertOne {
	_c.conflict = opts
	return &OrgUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Org.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OrgCreate) OnConflictColumns(columns ...string) *OrgUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OrgUpsertOne{
		create: _c,
	}
}

type (
	// OrgUpsertOne is the builder for "upsert"-ing
	//  one Org node.
	OrgUpsertOne struct {
		create *OrgCreate
	}

	// OrgUpsert is the "OnConflict" setter.
	OrgUpsert struct {
		*sql.UpdateSet
	}
)

// SetOwnerID sets the "owner_id" field.
func (u *OrgUpsert) SetOwnerID(v int) *OrgUpsert {
	u.Set(org.FieldOwnerID, v)
	return u
}

// UpdateOwnerID sets the "owner_id" field to the value that was provided on create.
func (u *OrgUpsert) UpdateOwnerID() *OrgUpsert {
	u.SetExcluded(org.FieldOwnerID)
	return u
}

// AddOwnerID adds v to the "owner_id" field.
func (u *OrgUpsert) AddOwnerID(v int) *OrgUpsert {
	u.Add(org.FieldOwnerID, v)
	return u
}

// ClearOwnerID clears the value of the "owner_id" field.
func (u *OrgUpsert) ClearOwnerID() *OrgUpsert {
	u.SetNull(org.FieldOwnerID)
	return u
}

// SetKind sets the "kind" field.
func (u *OrgUpsert) SetKind(v string) *OrgUpsert {
	u.Set(org.FieldKind, v)
	return u
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *OrgUpsert) UpdateKind() *OrgUpsert {
	u.SetExcluded(org.FieldKind)
	return u
}

// ClearKind clears the value of the "kind" field.
func (u *OrgUpsert) ClearKind() *OrgUpsert {
	u.SetNull(org.FieldKind)
	return u
}

// SetParentID sets the "parent_id" field.
func (u *OrgUpsert) SetParentID(v int) *OrgUpsert {
	u.Set(org.FieldParentID, v)
	return u
}

// UpdateParentID sets the "parent_id" field to the value that was provided on create.
func (u *OrgUpsert) UpdateParentID() *OrgUpsert {
	u.SetExcluded(org.FieldParentID)
	return u
}

// AddParentID adds v to the "parent_id" field.
func (u *OrgUpsert) AddParentID(v int) *OrgUpsert {
	u.Add(org.FieldParentID, v)
	return u
}

// ClearParentID clears the value of the "parent_id" field.
func (u *OrgUpsert) ClearParentID() *OrgUpsert {
	u.SetNull(org.FieldParentID)
	return u
}

// SetPath sets the "path" field.
func (u *OrgUpsert) SetPath(v string) *OrgUpsert {
	u.Set(org.FieldPath, v)
	return u
}

// UpdatePath sets the "path" field to the value that was provided on create.
func (u *OrgUpsert) UpdatePath() *OrgUpsert {
	u.SetExcluded(org.FieldPath)
	return u
}

// ClearPath clears the value of the "path" field.
func (u *OrgUpsert) ClearPath() *OrgUpsert {
	u.SetNull(org.FieldPath)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Org.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(org.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *OrgUpsertOne) UpdateNewValues() *OrgUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(org.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Org.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OrgUpsertOne) Ignore() *OrgUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OrgUpsertOne) DoNothing() *OrgUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OrgCreate.OnConflict
// documentation for more info.
func (u *OrgUpsertOne) Update(set func(*OrgUpsert)) *OrgUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OrgUpsert{UpdateSet: update})
	}))
	return u
}

// SetOwnerID sets the "owner_id" field.
func (u *OrgUpsertOne) SetOwnerID(v int) *OrgUpsertOne {
	return u.Update(func(s *OrgUpsert) {
		s.SetOwnerID(v)
	})
}

// AddOwnerID adds v to the "owner_id" field.
func (u *OrgUpsertOne) AddOwnerID(v int) *OrgUpsertOne {
	return u.Update(func(s *OrgUpsert) {
		s.AddOwnerID(v)
	})
}

// UpdateOwnerID sets the "owner_id" field to the value that was provided on create.
func (u *OrgUpsertOne) UpdateOwnerID() *OrgUpsertOne {
	return u.Update(func(s *OrgUpsert) {
		s.UpdateOwnerID()
	})
}

// ClearOwnerID clears the value of the "owner_id" field.
func (u *OrgUpsertOne) ClearOwnerID() *OrgUpsertOne {
	return u.Update(func(s *OrgUpsert) {
		s.ClearOwnerID()
	})
}

// SetKind sets the "kind" field.
func (u *OrgUpsertOne) SetKind(v string) *OrgUpsertOne {
	return u.Update(func(s *OrgUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *OrgUpsertOne) UpdateKind() *OrgUpsertOne {
	return u.Update(func(s *OrgUpsert) {
		s.UpdateKind()
	})
}

// ClearKind clears the value of the "kind" field.
func (u *OrgUpsertOne) ClearKind() *OrgUpsertOne {
	return u.Update(func(s *OrgUpsert) {
		s.ClearKind()
	})
}

// SetParentID sets the "parent_id" field.
func (u *OrgUpsertOne) SetParentID(v int) *OrgUpsertOne {
	return u.Update(func(s *OrgUpsert) {
		s.SetParentID(v)
	})
}

// AddParentID adds v to the "parent_id" field.
func (u *OrgUpsertOne) AddParentID(v int) *OrgUpsertOne {
	return u.Update(func(s *OrgUpsert) {
		s.AddParentID(v)
	})
}

// UpdateParentID sets the "parent_id" field to the value that was provided on create.
func (u *OrgUpsertOne) UpdateParentID() *OrgUpsertOne {
	return u.Update(func(s *OrgUpsert) {
		s.UpdateParentID()
	})
}

// ClearParentID clears the value of the "parent_id" field.
func (u *OrgUpsertOne) ClearParentID() *OrgUpsertOne {
	return u.Update(func(s *OrgUpsert) {
		s.ClearParentID()
	})
}

// SetPath sets the "path" field.
func (u *OrgUpsertOne) SetPath(v string) *OrgUpsertOne {
	return u.Update(func(s *OrgUpsert) {
		s.SetPath(v)
	})
}

// UpdatePath sets the "path" field to the value that was provided on create.
func (u *OrgUpsertOne) UpdatePath() *OrgUpsertOne {
	return u.Update(func(s *OrgUpsert) {
		s.UpdatePath()
	})
}

// ClearPath clears the value of the "path" field.
func (u *OrgUpsertOne) ClearPath() *OrgUpsertOne {
	return u.Update(func(s *OrgUpsert) {
		s.ClearPath()
	})
}

// Exec executes the query.
func (u *OrgUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OrgCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OrgUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OrgUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OrgUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OrgCreateBulk is the builder for creating many Org entities in bulk.
type OrgCreateBulk struct {
	config
	err      error
	builders []*OrgCreate
	conflict []sql.ConflictOption
}

// Save creates the Org entities in the database.
func (_c *OrgCreateBulk) Save(ctx context.Context) ([]*Org, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Org, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OrgMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OrgCreateBulk) SaveX(ctx context.Context) []*Org {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrgCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrgCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Org.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OrgUpsert) {
//			SetOwnerID(v+v).
//		}).
//		Exec(ctx)
func (_c *OrgCreateBulk) OnConflict(opts ...sql.ConflictOption) *OrgUpsertBulk {
	_c.conflict = opts
	return &OrgUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Org.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OrgCreateBulk) OnConflictColumns(columns ...string) *OrgUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OrgUpsertBulk{
		create: _c,
	}
}

// OrgUpsertBulk is the builder for "upsert"-ing
// a bulk of Org nodes.
type OrgUpsertBulk struct {
	create *OrgCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Org.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(org.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *OrgUpsertBulk) UpdateNewValues() *OrgUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(org.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Org.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OrgUpsertBulk) Ignore() *OrgUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OrgUpsertBulk) DoNothing() *OrgUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OrgCreateBulk.OnConflict
// documentation for more info.
func (u *OrgUpsertBulk) Update(set func(*OrgUpsert)) *OrgUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OrgUpsert{UpdateSet: update})
	}))
	return u
}

// SetOwnerID sets the "owner_id" field.
func (u *OrgUpsertBulk) SetOwnerID(v int) *OrgUpsertBulk {
	return u.Update(func(s *OrgUpsert) {
		s.SetOwnerID(v)
	})
}

// AddOwnerID adds v to the "owner_id" field.
func (u *OrgUpsertBulk) AddOwnerID(v int) *OrgUpsertBulk {
	return u.Update(func(s *OrgUpsert) {
		s.AddOwnerID(v)
	})
}

// UpdateOwnerID sets the "owner_id" field to the value that was provided on create.
func (u *OrgUpsertBulk) UpdateOwnerID() *OrgUpsertBulk {
	return u.Update(func(s *OrgUpsert) {
		s.UpdateOwnerID()
	})
}

// ClearOwnerID clears the value of the "owner_id" field.
func (u *OrgUpsertBulk) ClearOwnerID() *OrgUpsertBulk {
	return u.Update(func(s *OrgUpsert) {
		s.ClearOwnerID()
	})
}

// SetKind sets the "kind" field.
func (u *OrgUpsertBulk) SetKind(v string) *OrgUpsertBulk {
	return u.Update(func(s *OrgUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *OrgUpsertBulk) UpdateKind() *OrgUpsertBulk {
	return u.Update(func(s *OrgUpsert) {
		s.UpdateKind()
	})
}

// ClearKind clears the value of the "kind" field.
func (u *OrgUpsertBulk) ClearKind() *OrgUpsertBulk {
	return u.Update(func(s *OrgUpsert) {
		s.ClearKind()
	})
}

// SetParentID sets the "parent_id" field.
func (u *OrgUpsertBulk) SetParentID(v int) *OrgUpsertBulk {
	return u.Update(func(s *OrgUpsert) {
		s.SetParentID(v)
	})
}

// AddParentID adds v to the "parent_id" field.
func (u *OrgUpsertBulk) AddParentID(v int) *OrgUpsertBulk {
	return u.Update(func(s *OrgUpsert) {
		s.AddParentID(v)
	})
}

// UpdateParentID sets the "parent_id" field to the value that was provided on create.
func (u *OrgUpsertBulk) UpdateParentID() *OrgUpsertBulk {
	return u.Update(func(s *OrgUpsert) {
		s.UpdateParentID()
	})
}

// ClearParentID clears the value of the "parent_id" field.
func (u *OrgUpsertBulk) ClearParentID() *OrgUpsertBulk {
	return u.Update(func(s *OrgUpsert) {
		s.ClearParentID()
	})
}

// SetPath sets the "path" field.
func (u *OrgUpsertBulk) SetPath(v string) *OrgUpsertBulk {
	return u.Update(func(s *OrgUpsert) {
		s.SetPath(v)
	})
}

// UpdatePath sets the "path" field to the value that was provided on create.
func (u *OrgUpsertBulk) UpdatePath() *OrgUpsertBulk {
	return u.Update(func(s *OrgUpsert) {
		s.UpdatePath()
	})
}

// ClearPath clears the value of the "path" field.
func (u *OrgUpsertBulk) ClearPath() *OrgUpsertBulk {
	return u.Update(func(s *OrgUpsert) {
		s.ClearPath()
	})
}

// Exec executes the query.
func (u *OrgUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OrgCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OrgCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OrgUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
