// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/woocoos/msgcenter/ent/predicate"
	"github.com/woocoos/msgcenter/ent/useraddr"

	"github.com/woocoos/msgcenter/ent/internal"
)

// UserAddrUpdate is the builder for updating UserAddr entities.
type UserAddrUpdate struct {
	config
	hooks    []Hook
	mutation *UserAddrMutation
}

// Where appends a list predicates to the UserAddrUpdate builder.
func (_u *UserAddrUpdate) Where(ps ...predicate.UserAddr) *UserAddrUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAddrType sets the "addr_type" field.
func (_u *UserAddrUpdate) SetAddrType(v useraddr.AddrType) *UserAddrUpdate {
	_u.mutation.SetAddrType(v)
	return _u
}

// SetNillableAddrType sets the "addr_type" field if the given value is not nil.
func (_u *UserAddrUpdate) SetNillableAddrType(v *useraddr.AddrType) *UserAddrUpdate {
	if v != nil {
		_u.SetAddrType(*v)
	}
	return _u
}

// SetRegionID sets the "region_id" field.
func (_u *UserAddrUpdate) SetRegionID(v int) *UserAddrUpdate {
	_u.mutation.ResetRegionID()
	_u.mutation.SetRegionID(v)
	return _u
}

// SetNillableRegionID sets the "region_id" field if the given value is not nil.
func (_u *UserAddrUpdate) SetNillableRegionID(v *int) *UserAddrUpdate {
	if v != nil {
		_u.SetRegionID(*v)
	}
	return _u
}

// AddRegionID adds value to the "region_id" field.
func (_u *UserAddrUpdate) AddRegionID(v int) *UserAddrUpdate {
	_u.mutation.AddRegionID(v)
	return _u
}

// ClearRegionID clears the value of the "region_id" field.
func (_u *UserAddrUpdate) ClearRegionID() *UserAddrUpdate {
	_u.mutation.ClearRegionID()
	return _u
}

// SetAddr sets the "addr" field.
func (_u *UserAddrUpdate) SetAddr(v string) *UserAddrUpdate {
	_u.mutation.SetAddr(v)
	return _u
}

// SetNillableAddr sets the "addr" field if the given value is not nil.
func (_u *UserAddrUpdate) SetNillableAddr(v *string) *UserAddrUpdate {
	if v != nil {
		_u.SetAddr(*v)
	}
	return _u
}

// ClearAddr clears the value of the "addr" field.
func (_u *UserAddrUpdate) ClearAddr() *UserAddrUpdate {
	_u.mutation.ClearAddr()
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserAddrUpdate) SetEmail(v string) *UserAddrUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserAddrUpdate) SetNillableEmail(v *string) *UserAddrUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// ClearEmail clears the value of the "email" field.
func (_u *UserAddrUpdate) ClearEmail() *UserAddrUpdate {
	_u.mutation.ClearEmail()
	return _u
}

// SetFax sets the "fax" field.
func (_u *UserAddrUpdate) SetFax(v string) *UserAddrUpdate {
	_u.mutation.SetFax(v)
	return _u
}

// SetNillableFax sets the "fax" field if the given value is not nil.
func (_u *UserAddrUpdate) SetNillableFax(v *string) *UserAddrUpdate {
	if v != nil {
		_u.SetFax(*v)
	}
	return _u
}

// ClearFax clears the value of the "fax" field.
func (_u *UserAddrUpdate) ClearFax() *UserAddrUpdate {
	_u.mutation.ClearFax()
	return _u
}

// SetZipCode sets the "zip_code" field.
func (_u *UserAddrUpdate) SetZipCode(v string) *UserAddrUpdate {
	_u.mutation.SetZipCode(v)
	return _u
}

// SetNillableZipCode sets the "zip_code" field if the given value is not nil.
func (_u *UserAddrUpdate) SetNillableZipCode(v *string) *UserAddrUpdate {
	if v != nil {
		_u.SetZipCode(*v)
	}
	return _u
}

// ClearZipCode clears the value of the "zip_code" field.
func (_u *UserAddrUpdate) ClearZipCode() *UserAddrUpdate {
	_u.mutation.ClearZipCode()
	return _u
}

// SetTel sets the "tel" field.
func (_u *UserAddrUpdate) SetTel(v string) *UserAddrUpdate {
	_u.mutation.SetTel(v)
	return _u
}

// SetNillableTel sets the "tel" field if the given value is not nil.
func (_u *UserAddrUpdate) SetNillableTel(v *string) *UserAddrUpdate {
	if v != nil {
		_u.SetTel(*v)
	}
	return _u
}

// ClearTel clears the value of the "tel" field.
func (_u *UserAddrUpdate) ClearTel() *UserAddrUpdate {
	_u.mutation.ClearTel()
	return _u
}

// SetMobile sets the "mobile" field.
func (_u *UserAddrUpdate) SetMobile(v string) *UserAddrUpdate {
	_u.mutation.SetMobile(v)
	return _u
}

// SetNillableMobile sets the "mobile" field if the given value is not nil.
func (_u *UserAddrUpdate) SetNillableMobile(v *string) *UserAddrUpdate {
	if v != nil {
		_u.SetMobile(*v)
	}
	return _u
}

// ClearMobile clears the value of the "mobile" field.
func (_u *UserAddrUpdate) ClearMobile() *UserAddrUpdate {
	_u.mutation.ClearMobile()
	return _u
}

// SetName sets the "name" field.
func (_u *UserAddrUpdate) SetName(v string) *UserAddrUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UserAddrUpdate) SetNillableName(v *string) *UserAddrUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *UserAddrUpdate) ClearName() *UserAddrUpdate {
	_u.mutation.ClearName()
	return _u
}

// SetIsDefault sets the "is_default" field.
func (_u *UserAddrUpdate) SetIsDefault(v bool) *UserAddrUpdate {
	_u.mutation.SetIsDefault(v)
	return _u
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_u *UserAddrUpdate) SetNillableIsDefault(v *bool) *UserAddrUpdate {
	if v != nil {
		_u.SetIsDefault(*v)
	}
	return _u
}

// Mutation returns the UserAddrMutation object of the builder.
func (_u *UserAddrUpdate) Mutation() *UserAddrMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserAddrUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserAddrUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserAddrUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserAddrUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserAddrUpdate) check() error {
	if v, ok := _u.mutation.AddrType(); ok {
		if err := useraddr.AddrTypeValidator(v); err != nil {
			return &ValidationError{Name: "addr_type", err: fmt.Errorf(`ent: validator failed for field "UserAddr.addr_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := useraddr.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "UserAddr.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Fax(); ok {
		if err := useraddr.FaxValidator(v); err != nil {
			return &ValidationError{Name: "fax", err: fmt.Errorf(`ent: validator failed for field "UserAddr.fax": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ZipCode(); ok {
		if err := useraddr.ZipCodeValidator(v); err != nil {
			return &ValidationError{Name: "zip_code", err: fmt.Errorf(`ent: validator failed for field "UserAddr.zip_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Tel(); ok {
		if err := useraddr.TelValidator(v); err != nil {
			return &ValidationError{Name: "tel", err: fmt.Errorf(`ent: validator failed for field "UserAddr.tel": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Mobile(); ok {
		if err := useraddr.MobileValidator(v); err != nil {
			return &ValidationError{Name: "mobile", err: fmt.Errorf(`ent: validator failed for field "UserAddr.mobile": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := useraddr.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "UserAddr.name": %w`, err)}
		}
	}
	return nil
}

func (_u *UserAddrUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(useraddr.Table, useraddr.Columns, sqlgraph.NewFieldSpec(useraddr.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AddrType(); ok {
		_spec.SetField(useraddr.FieldAddrType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.RegionID(); ok {
		_spec.SetField(useraddr.FieldRegionID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRegionID(); ok {
		_spec.AddField(useraddr.FieldRegionID, field.TypeInt, value)
	}
	if _u.mutation.RegionIDCleared() {
		_spec.ClearField(useraddr.FieldRegionID, field.TypeInt)
	}
	if value, ok := _u.mutation.Addr(); ok {
		_spec.SetField(useraddr.FieldAddr, field.TypeString, value)
	}
	if _u.mutation.AddrCleared() {
		_spec.ClearField(useraddr.FieldAddr, field.TypeString)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(useraddr.FieldEmail, field.TypeString, value)
	}
	if _u.mutation.EmailCleared() {
		_spec.ClearField(useraddr.FieldEmail, field.TypeString)
	}
	if value, ok := _u.mutation.Fax(); ok {
		_spec.SetField(useraddr.FieldFax, field.TypeString, value)
	}
	if _u.mutation.FaxCleared() {
		_spec.ClearField(useraddr.FieldFax, field.TypeString)
	}
	if value, ok := _u.mutation.ZipCode(); ok {
		_spec.SetField(useraddr.FieldZipCode, field.TypeString, value)
	}
	if _u.mutation.ZipCodeCleared() {
		_spec.ClearField(useraddr.FieldZipCode, field.TypeString)
	}
	if value, ok := _u.mutation.Tel(); ok {
		_spec.SetField(useraddr.FieldTel, field.TypeString, value)
	}
	if _u.mutation.TelCleared() {
		_spec.ClearField(useraddr.FieldTel, field.TypeString)
	}
	if value, ok := _u.mutation.Mobile(); ok {
		_spec.SetField(useraddr.FieldMobile, field.TypeString, value)
	}
	if _u.mutation.MobileCleared() {
		_spec.ClearField(useraddr.FieldMobile, field.TypeString)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(useraddr.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(useraddr.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.IsDefault(); ok {
		_spec.SetField(useraddr.FieldIsDefault, field.TypeBool, value)
	}
	_spec.Node.Schema = _u.schemaConfig.UserAddr
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{useraddr.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserAddrUpdateOne is the builder for updating a single UserAddr entity.
type UserAddrUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserAddrMutation
}

// SetAddrType sets the "addr_type" field.
func (_u *UserAddrUpdateOne) SetAddrType(v useraddr.AddrType) *UserAddrUpdateOne {
	_u.mutation.SetAddrType(v)
	return _u
}

// SetNillableAddrType sets the "addr_type" field if the given value is not nil.
func (_u *UserAddrUpdateOne) SetNillableAddrType(v *useraddr.AddrType) *UserAddrUpdateOne {
	if v != nil {
		_u.SetAddrType(*v)
	}
	return _u
}

// SetRegionID sets the "region_id" field.
func (_u *UserAddrUpdateOne) SetRegionID(v int) *UserAddrUpdateOne {
	_u.mutation.ResetRegionID()
	_u.mutation.SetRegionID(v)
	return _u
}

// SetNillableRegionID sets the "region_id" field if the given value is not nil.
func (_u *UserAddrUpdateOne) SetNillableRegionID(v *int) *UserAddrUpdateOne {
	if v != nil {
		_u.SetRegionID(*v)
	}
	return _u
}

// AddRegionID adds value to the "region_id" field.
func (_u *UserAddrUpdateOne) AddRegionID(v int) *UserAddrUpdateOne {
	_u.mutation.AddRegionID(v)
	return _u
}

// ClearRegionID clears the value of the "region_id" field.
func (_u *UserAddrUpdateOne) ClearRegionID() *UserAddrUpdateOne {
	_u.mutation.ClearRegionID()
	return _u
}

// SetAddr sets the "addr" field.
func (_u *UserAddrUpdateOne) SetAddr(v string) *UserAddrUpdateOne {
	_u.mutation.SetAddr(v)
	return _u
}

// SetNillableAddr sets the "addr" field if the given value is not nil.
func (_u *UserAddrUpdateOne) SetNillableAddr(v *string) *UserAddrUpdateOne {
	if v != nil {
		_u.SetAddr(*v)
	}
	return _u
}

// ClearAddr clears the value of the "addr" field.
func (_u *UserAddrUpdateOne) ClearAddr() *UserAddrUpdateOne {
	_u.mutation.ClearAddr()
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserAddrUpdateOne) SetEmail(v string) *UserAddrUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserAddrUpdateOne) SetNillableEmail(v *string) *UserAddrUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// ClearEmail clears the value of the "email" field.
func (_u *UserAddrUpdateOne) ClearEmail() *UserAddrUpdateOne {
	_u.mutation.ClearEmail()
	return _u
}

// SetFax sets the "fax" field.
func (_u *UserAddrUpdateOne) SetFax(v string) *UserAddrUpdateOne {
	_u.mutation.SetFax(v)
	return _u
}

// SetNillableFax sets the "fax" field if the given value is not nil.
func (_u *UserAddrUpdateOne) SetNillableFax(v *string) *UserAddrUpdateOne {
	if v != nil {
		_u.SetFax(*v)
	}
	return _u
}

// ClearFax clears the value of the "fax" field.
func (_u *UserAddrUpdateOne) ClearFax() *UserAddrUpdateOne {
	_u.mutation.ClearFax()
	return _u
}

// SetZipCode sets the "zip_code" field.
func (_u *UserAddrUpdateOne) SetZipCode(v string) *UserAddrUpdateOne {
	_u.mutation.SetZipCode(v)
	return _u
}

// SetNillableZipCode sets the "zip_code" field if the given value is not nil.
func (_u *UserAddrUpdateOne) SetNillableZipCode(v *string) *UserAddrUpdateOne {
	if v != nil {
		_u.SetZipCode(*v)
	}
	return _u
}

// ClearZipCode clears the value of the "zip_code" field.
func (_u *UserAddrUpdateOne) ClearZipCode() *UserAddrUpdateOne {
	_u.mutation.ClearZipCode()
	return _u
}

// SetTel sets the "tel" field.
func (_u *UserAddrUpdateOne) SetTel(v string) *UserAddrUpdateOne {
	_u.mutation.SetTel(v)
	return _u
}

// SetNillableTel sets the "tel" field if the given value is not nil.
func (_u *UserAddrUpdateOne) SetNillableTel(v *string) *UserAddrUpdateOne {
	if v != nil {
		_u.SetTel(*v)
	}
	return _u
}

// ClearTel clears the value of the "tel" field.
func (_u *UserAddrUpdateOne) ClearTel() *UserAddrUpdateOne {
	_u.mutation.ClearTel()
	return _u
}

// SetMobile sets the "mobile" field.
func (_u *UserAddrUpdateOne) SetMobile(v string) *UserAddrUpdateOne {
	_u.mutation.SetMobile(v)
	return _u
}

// SetNillableMobile sets the "mobile" field if the given value is not nil.
func (_u *UserAddrUpdateOne) SetNillableMobile(v *string) *UserAddrUpdateOne {
	if v != nil {
		_u.SetMobile(*v)
	}
	return _u
}

// ClearMobile clears the value of the "mobile" field.
func (_u *UserAddrUpdateOne) ClearMobile() *UserAddrUpdateOne {
	_u.mutation.ClearMobile()
	return _u
}

// SetName sets the "name" field.
func (_u *UserAddrUpdateOne) SetName(v string) *UserAddrUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UserAddrUpdateOne) SetNillableName(v *string) *UserAddrUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *UserAddrUpdateOne) ClearName() *UserAddrUpdateOne {
	_u.mutation.ClearName()
	return _u
}

// SetIsDefault sets the "is_default" field.
func (_u *UserAddrUpdateOne) SetIsDefault(v bool) *UserAddrUpdateOne {
	_u.mutation.SetIsDefault(v)
	return _u
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_u *UserAddrUpdateOne) SetNillableIsDefault(v *bool) *UserAddrUpdateOne {
	if v != nil {
		_u.SetIsDefault(*v)
	}
	return _u
}

// Mutation returns the UserAddrMutation object of the builder.
func (_u *UserAddrUpdateOne) Mutation() *UserAddrMutation {
	return _u.mutation
}

// Where appends a list predicates to the UserAddrUpdate builder.
func (_u *UserAddrUpdateOne) Where(ps ...predicate.UserAddr) *UserAddrUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserAddrUpdateOne) Select(field string, fields ...string) *UserAddrUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserAddr entity.
func (_u *UserAddrUpdateOne) Save(ctx context.Context) (*UserAddr, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserAddrUpdateOne) SaveX(ctx context.Context) *UserAddr {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserAddrUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserAddrUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserAddrUpdateOne) check() error {
	if v, ok := _u.mutation.AddrType(); ok {
		if err := useraddr.AddrTypeValidator(v); err != nil {
			return &ValidationError{Name: "addr_type", err: fmt.Errorf(`ent: validator failed for field "UserAddr.addr_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := useraddr.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "UserAddr.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Fax(); ok {
		if err := useraddr.FaxValidator(v); err != nil {
			return &ValidationError{Name: "fax", err: fmt.Errorf(`ent: validator failed for field "UserAddr.fax": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ZipCode(); ok {
		if err := useraddr.ZipCodeValidator(v); err != nil {
			return &ValidationError{Name: "zip_code", err: fmt.Errorf(`ent: validator failed for field "UserAddr.zip_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Tel(); ok {
		if err := useraddr.TelValidator(v); err != nil {
			return &ValidationError{Name: "tel", err: fmt.Errorf(`ent: validator failed for field "UserAddr.tel": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Mobile(); ok {
		if err := useraddr.MobileValidator(v); err != nil {
			return &ValidationError{Name: "mobile", err: fmt.Errorf(`ent: validator failed for field "UserAddr.mobile": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := useraddr.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "UserAddr.name": %w`, err)}
		}
	}
	return nil
}

func (_u *UserAddrUpdateOne) sqlSave(ctx context.Context) (_node *UserAddr, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(useraddr.Table, useraddr.Columns, sqlgraph.NewFieldSpec(useraddr.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserAddr.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, useraddr.FieldID)
		for _, f := range fields {
			if !useraddr.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != useraddr.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AddrType(); ok {
		_spec.SetField(useraddr.FieldAddrType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.RegionID(); ok {
		_spec.SetField(useraddr.FieldRegionID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRegionID(); ok {
		_spec.AddField(useraddr.FieldRegionID, field.TypeInt, value)
	}
	if _u.mutation.RegionIDCleared() {
		_spec.ClearField(useraddr.FieldRegionID, field.TypeInt)
	}
	if value, ok := _u.mutation.Addr(); ok {
		_spec.SetField(useraddr.FieldAddr, field.TypeString, value)
	}
	if _u.mutation.AddrCleared() {
		_spec.ClearField(useraddr.FieldAddr, field.TypeString)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(useraddr.FieldEmail, field.TypeString, value)
	}
	if _u.mutation.EmailCleared() {
		_spec.ClearField(useraddr.FieldEmail, field.TypeString)
	}
	if value, ok := _u.mutation.Fax(); ok {
		_spec.SetField(useraddr.FieldFax, field.TypeString, value)
	}
	if _u.mutation.FaxCleared() {
		_spec.ClearField(useraddr.FieldFax, field.TypeString)
	}
	if value, ok := _u.mutation.ZipCode(); ok {
		_spec.SetField(useraddr.FieldZipCode, field.TypeString, value)
	}
	if _u.mutation.ZipCodeCleared() {
		_spec.ClearField(useraddr.FieldZipCode, field.TypeString)
	}
	if value, ok := _u.mutation.Tel(); ok {
		_spec.SetField(useraddr.FieldTel, field.TypeString, value)
	}
	if _u.mutation.TelCleared() {
		_spec.ClearField(useraddr.FieldTel, field.TypeString)
	}
	if value, ok := _u.mutation.Mobile(); ok {
		_spec.SetField(useraddr.FieldMobile, field.TypeString, value)
	}
	if _u.mutation.MobileCleared() {
		_spec.ClearField(useraddr.FieldMobile, field.TypeString)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(useraddr.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(useraddr.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.IsDefault(); ok {
		_spec.SetField(useraddr.FieldIsDefault, field.TypeBool, value)
	}
	_spec.Node.Schema = _u.schemaConfig.UserAddr
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	_node = &UserAddr{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{useraddr.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
