// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/woocoos/knockout-go/ent/schemax/typex"
	"github.com/woocoos/msgcenter/ent/userdevice"
)

// UserDeviceCreate is the builder for creating a UserDevice entity.
type UserDeviceCreate struct {
	config
	mutation *UserDeviceMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *UserDeviceCreate) SetUserID(v int) *UserDeviceCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *UserDeviceCreate) SetNillableUserID(v *int) *UserDeviceCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetDeviceUID sets the "device_uid" field.
func (_c *UserDeviceCreate) SetDeviceUID(v string) *UserDeviceCreate {
	_c.mutation.SetDeviceUID(v)
	return _c
}

// SetDeviceName sets the "device_name" field.
func (_c *UserDeviceCreate) SetDeviceName(v string) *UserDeviceCreate {
	_c.mutation.SetDeviceName(v)
	return _c
}

// SetNillableDeviceName sets the "device_name" field if the given value is not nil.
func (_c *UserDeviceCreate) SetNillableDeviceName(v *string) *UserDeviceCreate {
	if v != nil {
		_c.SetDeviceName(*v)
	}
	return _c
}

// SetSystemName sets the "system_name" field.
func (_c *UserDeviceCreate) SetSystemName(v string) *UserDeviceCreate {
	_c.mutation.SetSystemName(v)
	return _c
}

// SetNillableSystemName sets the "system_name" field if the given value is not nil.
func (_c *UserDeviceCreate) SetNillableSystemName(v *string) *UserDeviceCreate {
	if v != nil {
		_c.SetSystemName(*v)
	}
	return _c
}

// SetSystemVersion sets the "system_version" field.
func (_c *UserDeviceCreate) SetSystemVersion(v string) *UserDeviceCreate {
	_c.mutation.SetSystemVersion(v)
	return _c
}

// SetNillableSystemVersion sets the "system_version" field if the given value is not nil.
func (_c *UserDeviceCreate) SetNillableSystemVersion(v *string) *UserDeviceCreate {
	if v != nil {
		_c.SetSystemVersion(*v)
	}
	return _c
}

// SetAppVersion sets the "app_version" field.
func (_c *UserDeviceCreate) SetAppVersion(v string) *UserDeviceCreate {
	_c.mutation.SetAppVersion(v)
	return _c
}

// SetNillableAppVersion sets the "app_version" field if the given value is not nil.
func (_c *UserDeviceCreate) SetNillableAppVersion(v *string) *UserDeviceCreate {
	if v != nil {
		_c.SetAppVersion(*v)
	}
	return _c
}

// SetDeviceModel sets the "device_model" field.
func (_c *UserDeviceCreate) SetDeviceModel(v string) *UserDeviceCreate {
	_c.mutation.SetDeviceModel(v)
	return _c
}

// SetNillableDeviceModel sets the "device_model" field if the given value is not nil.
func (_c *UserDeviceCreate) SetNillableDeviceModel(v *string) *UserDeviceCreate {
	if v != nil {
		_c.SetDeviceModel(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *UserDeviceCreate) SetStatus(v typex.SimpleStatus) *UserDeviceCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *UserDeviceCreate) SetNillableStatus(v *typex.SimpleStatus) *UserDeviceCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *UserDeviceCreate) SetID(v int) *UserDeviceCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the UserDeviceMutation object of the builder.
func (_c *UserDeviceCreate) Mutation() *UserDeviceMutation {
	return _c.mutation
}

// Save creates the UserDevice in the database.
func (_c *UserDeviceCreate) Save(ctx context.Context) (*UserDevice, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserDeviceCreate) SaveX(ctx context.Context) *UserDevice {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserDeviceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserDeviceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserDeviceCreate) check() error {
	if _, ok := _c.mutation.DeviceUID(); !ok {
		return &ValidationError{Name: "device_uid", err: errors.New(`ent: missing required field "UserDevice.device_uid"`)}
	}
	if v, ok := _c.mutation.DeviceUID(); ok {
		if err := userdevice.DeviceUIDValidator(v); err != nil {
			return &ValidationError{Name: "device_uid", err: fmt.Errorf(`ent: validator failed for field "UserDevice.device_uid": %w`, err)}
		}
	}
	if v, ok := _c.mutation.DeviceName(); ok {
		if err := userdevice.DeviceNameValidator(v); err != nil {
			return &ValidationError{Name: "device_name", err: fmt.Errorf(`ent: validator failed for field "UserDevice.device_name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.SystemName(); ok {
		if err := userdevice.SystemNameValidator(v); err != nil {
			return &ValidationError{Name: "system_name", err: fmt.Errorf(`ent: validator failed for field "UserDevice.system_name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.SystemVersion(); ok {
		if err := userdevice.SystemVersionValidator(v); err != nil {
			return &ValidationError{Name: "system_version", err: fmt.Errorf(`ent: validator failed for field "UserDevice.system_version": %w`, err)}
		}
	}
	if v, ok := _c.mutation.AppVersion(); ok {
		if err := userdevice.AppVersionValidator(v); err != nil {
			return &ValidationError{Name: "app_version", err: fmt.Errorf(`ent: validator failed for field "UserDevice.app_version": %w`, err)}
		}
	}
	if v, ok := _c.mutation.DeviceModel(); ok {
		if err := userdevice.DeviceModelValidator(v); err != nil {
			return &ValidationError{Name: "device_model", err: fmt.Errorf(`ent: validator failed for field "UserDevice.device_model": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := userdevice.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UserDevice.status": %w`, err)}
		}
	}
	return nil
}

func (_c *UserDeviceCreate) sqlSave(ctx context.Context) (*UserDevice, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserDeviceCreate) createSpec() (*UserDevice, *sqlgraph.CreateSpec) {
	var (
		_node = &UserDevice{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(userdevice.Table, sqlgraph.NewFieldSpec(userdevice.FieldID, field.TypeInt))
	)
	_spec.Schema = _c.schemaConfig.UserDevice
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(userdevice.FieldUserID, field.TypeInt, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.DeviceUID(); ok {
		_spec.SetField(userdevice.FieldDeviceUID, field.TypeString, value)
		_node.DeviceUID = value
	}
	if value, ok := _c.mutation.DeviceName(); ok {
		_spec.SetField(userdevice.FieldDeviceName, field.TypeString, value)
		_node.DeviceName = value
	}
	if value, ok := _c.mutation.SystemName(); ok {
		_spec.SetField(userdevice.FieldSystemName, field.TypeString, value)
		_node.SystemName = value
	}
	if value, ok := _c.mutation.SystemVersion(); ok {
		_spec.SetField(userdevice.FieldSystemVersion, field.TypeString, value)
		_node.SystemVersion = value
	}
	if value, ok := _c.mutation.AppVersion(); ok {
		_spec.SetField(userdevice.FieldAppVersion, field.TypeString, value)
		_node.AppVersion = value
	}
	if value, ok := _c.mutation.DeviceModel(); ok {
		_spec.SetField(userdevice.FieldDeviceModel, field.TypeString, value)
		_node.DeviceModel = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(userdevice.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserDevice.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserDeviceUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserDeviceCreate) OnConflict(opts ...sql.ConflictOption) *UserDeviceUpsertOne {
	_c.conflict = opts
	return &UserDeviceUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserDevice.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserDeviceCreate) OnConflictColumns(columns ...string) *UserDeviceUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserDeviceUpsertOne{
		create: _c,
	}
}

type (
	// UserDeviceUpsertOne is the builder for "upsert"-ing
	//  one UserDevice node.
	UserDeviceUpsertOne struct {
		create *UserDeviceCreate
	}

	// UserDeviceUpsert is the "OnConflict" setter.
	UserDeviceUpsert struct {
		*sql.UpdateSet
	}
)

// SetDeviceUID sets the "device_uid" field.
func (u *UserDeviceUpsert) SetDeviceUID(v string) *UserDeviceUpsert {
	u.Set(userdevice.FieldDeviceUID, v)
	return u
}

// UpdateDeviceUID sets the "device_uid" field to the value that was provided on create.
func (u *UserDeviceUpsert) UpdateDeviceUID() *UserDeviceUpsert {
	u.SetExcluded(userdevice.FieldDeviceUID)
	return u
}

// SetDeviceName sets the "device_name" field.
func (u *UserDeviceUpsert) SetDeviceName(v string) *UserDeviceUpsert {
	u.Set(userdevice.FieldDeviceName, v)
	return u
}

// UpdateDeviceName sets the "device_name" field to the value that was provided on create.
func (u *UserDeviceUpsert) UpdateDeviceName() *UserDeviceUpsert {
	u.SetExcluded(userdevice.FieldDeviceName)
	return u
}

// ClearDeviceName clears the value of the "device_name" field.
func (u *UserDeviceUpsert) ClearDeviceName() *UserDeviceUpsert {
	u.SetNull(userdevice.FieldDeviceName)
	return u
}

// SetSystemName sets the "system_name" field.
func (u *UserDeviceUpsert) SetSystemName(v string) *UserDeviceUpsert {
	u.Set(userdevice.FieldSystemName, v)
	return u
}

// UpdateSystemName sets the "system_name" field to the value that was provided on create.
func (u *UserDeviceUpsert) UpdateSystemName() *UserDeviceUpsert {
	u.SetExcluded(userdevice.FieldSystemName)
	return u
}

// ClearSystemName clears the value of the "system_name" field.
func (u *UserDeviceUpsert) ClearSystemName() *UserDeviceUpsert {
	u.SetNull(userdevice.FieldSystemName)
	return u
}

// SetSystemVersion sets the "system_version" field.
func (u *UserDeviceUpsert) SetSystemVersion(v string) *UserDeviceUpsert {
	u.Set(userdevice.FieldSystemVersion, v)
	return u
}

// UpdateSystemVersion sets the "system_version" field to the value that was provided on create.
func (u *UserDeviceUpsert) UpdateSystemVersion() *UserDeviceUpsert {
	u.SetExcluded(userdevice.FieldSystemVersion)
	return u
}

// ClearSystemVersion clears the value of the "system_version" field.
func (u *UserDeviceUpsert) ClearSystemVersion() *UserDeviceUpsert {
	u.SetNull(userdevice.FieldSystemVersion)
	return u
}

// SetAppVersion sets the "app_version" field.
func (u *UserDeviceUpsert) SetAppVersion(v string) *UserDeviceUpsert {
	u.Set(userdevice.FieldAppVersion, v)
	return u
}

// UpdateAppVersion sets the "app_version" field to the value that was provided on create.
func (u *UserDeviceUpsert) UpdateAppVersion() *UserDeviceUpsert {
	u.SetExcluded(userdevice.FieldAppVersion)
	return u
}

// ClearAppVersion clears the value of the "app_version" field.
func (u *UserDeviceUpsert) ClearAppVersion() *UserDeviceUpsert {
	u.SetNull(userdevice.FieldAppVersion)
	return u
}

// SetDeviceModel sets the "device_model" field.
func (u *UserDeviceUpsert) SetDeviceModel(v string) *UserDeviceUpsert {
	u.Set(userdevice.FieldDeviceModel, v)
	return u
}

// UpdateDeviceModel sets the "device_model" field to the value that was provided on create.
func (u *UserDeviceUpsert) UpdateDeviceModel() *UserDeviceUpsert {
	u.SetExcluded(userdevice.FieldDeviceModel)
	return u
}

// ClearDeviceModel clears the value of the "device_model" field.
func (u *UserDeviceUpsert) ClearDeviceModel() *UserDeviceUpsert {
	u.SetNull(userdevice.FieldDeviceModel)
	return u
}

// SetStatus sets the "status" field.
func (u *UserDeviceUpsert) SetStatus(v typex.SimpleStatus) *UserDeviceUpsert {
	u.Set(userdevice.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UserDeviceUpsert) UpdateStatus() *UserDeviceUpsert {
	u.SetExcluded(userdevice.FieldStatus)
	return u
}

// ClearStatus clears the value of the "status" field.
func (u *UserDeviceUpsert) ClearStatus() *UserDeviceUpsert {
	u.SetNull(userdevice.FieldStatus)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.UserDevice.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(userdevice.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *UserDeviceUpsertOne) UpdateNewValues() *UserDeviceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(userdevice.FieldID)
		}
		if _, exists := u.create.mutation.UserID(); exists {
			s.SetIgnore(userdevice.FieldUserID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserDevice.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserDeviceUpsertOne) Ignore() *UserDeviceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserDeviceUpsertOne) DoNothing() *UserDeviceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserDeviceCreate.OnConflict
// documentation for more info.
func (u *UserDeviceUpsertOne) Update(set func(*UserDeviceUpsert)) *UserDeviceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserDeviceUpsert{UpdateSet: update})
	}))
	return u
}

// SetDeviceUID sets the "device_uid" field.
func (u *UserDeviceUpsertOne) SetDeviceUID(v string) *UserDeviceUpsertOne {
	return u.Update(func(s *UserDeviceUpsert) {
		s.SetDeviceUID(v)
	})
}

// UpdateDeviceUID sets the "device_uid" field to the value that was provided on create.
func (u *UserDeviceUpsertOne) UpdateDeviceUID() *UserDeviceUpsertOne {
	return u.Update(func(s *UserDeviceUpsert) {
		s.UpdateDeviceUID()
	})
}

// SetDeviceName sets the "device_name" field.
func (u *UserDeviceUpsertOne) SetDeviceName(v string) *UserDeviceUpsertOne {
	return u.Update(func(s *UserDeviceUpsert) {
		s.SetDeviceName(v)
	})
}

// UpdateDeviceName sets the "device_name" field to the value that was provided on create.
func (u *UserDeviceUpsertOne) UpdateDeviceName() *UserDeviceUpsertOne {
	return u.Update(func(s *UserDeviceUpsert) {
		s.UpdateDeviceName()
	})
}

// ClearDeviceName clears the value of the "device_name" field.
func (u *UserDeviceUpsertOne) ClearDeviceName() *UserDeviceUpsertOne {
	return u.Update(func(s *UserDeviceUpsert) {
		s.ClearDeviceName()
	})
}

// SetSystemName sets the "system_name" field.
func (u *UserDeviceUpsertOne) SetSystemName(v string) *UserDeviceUpsertOne {
	return u.Update(func(s *UserDeviceUpsert) {
		s.SetSystemName(v)
	})
}

// UpdateSystemName sets the "system_name" field to the value that was provided on create.
func (u *UserDeviceUpsertOne) UpdateSystemName() *UserDeviceUpsertOne {
	return u.Update(func(s *UserDeviceUpsert) {
		s.UpdateSystemName()
	})
}

// ClearSystemName clears the value of the "system_name" field.
func (u *UserDeviceUpsertOne) ClearSystemName() *UserDeviceUpsertOne {
	return u.Update(func(s *UserDeviceUpsert) {
		s.ClearSystemName()
	})
}

// SetSystemVersion sets the "system_version" field.
func (u *UserDeviceUpsertOne) SetSystemVersion(v string) *UserDeviceUpsertOne {
	return u.Update(func(s *UserDeviceUpsert) {
		s.SetSystemVersion(v)
	})
}

// UpdateSystemVersion sets the "system_version" field to the value that was provided on create.
func (u *UserDeviceUpsertOne) UpdateSystemVersion() *UserDeviceUpsertOne {
	return u.Update(func(s *UserDeviceUpsert) {
		s.UpdateSystemVersion()
	})
}

// ClearSystemVersion clears the value of the "system_version" field.
func (u *UserDeviceUpsertOne) ClearSystemVersion() *UserDeviceUpsertOne {
	return u.Update(func(s *UserDeviceUpsert) {
		s.ClearSystemVersion()
	})
}

// SetAppVersion sets the "app_version" field.
func (u *UserDeviceUpsertOne) SetAppVersion(v string) *UserDeviceUpsertOne {
	return u.Update(func(s *UserDeviceUpsert) {
		s.SetAppVersion(v)
	})
}

// UpdateAppVersion sets the "app_version" field to the value that was provided on create.
func (u *UserDeviceUpsertOne) UpdateAppVersion() *UserDeviceUpsertOne {
	return u.Update(func(s *UserDeviceUpsert) {
		s.UpdateAppVersion()
	})
}

// ClearAppVersion clears the value of the "app_version" field.
func (u *UserDeviceUpsertOne) ClearAppVersion() *UserDeviceUpsertOne {
	return u.Update(func(s *UserDeviceUpsert) {
		s.ClearAppVersion()
	})
}

// SetDeviceModel sets the "device_model" field.
func (u *UserDeviceUpsertOne) SetDeviceModel(v string) *UserDeviceUpsertOne {
	return u.Update(func(s *UserDeviceUpsert) {
		s.SetDeviceModel(v)
	})
}

// UpdateDeviceModel sets the "device_model" field to the value that was provided on create.
func (u *UserDeviceUpsertOne) UpdateDeviceModel() *UserDeviceUpsertOne {
	return u.Update(func(s *UserDeviceUpsert) {
		s.UpdateDeviceModel()
	})
}

// ClearDeviceModel clears the value of the "device_model" field.
func (u *UserDeviceUpsertOne) ClearDeviceModel() *UserDeviceUpsertOne {
	return u.Update(func(s *UserDeviceUpsert) {
		s.ClearDeviceModel()
	})
}

// SetStatus sets the "status" field.
func (u *UserDeviceUpsertOne) SetStatus(v typex.SimpleStatus) *UserDeviceUpsertOne {
	return u.Update(func(s *UserDeviceUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UserDeviceUpsertOne) UpdateStatus() *UserDeviceUpsertOne {
	return u.Update(func(s *UserDeviceUpsert) {
		s.UpdateStatus()
	})
}

// ClearStatus clears the value of the "status" field.
func (u *UserDeviceUpsertOne) ClearStatus() *UserDeviceUpsertOne {
	return u.Update(func(s *UserDeviceUpsert) {
		s.ClearStatus()
	})
}

// Exec executes the query.
func (u *UserDeviceUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserDeviceCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserDeviceUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserDeviceUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserDeviceUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserDeviceCreateBulk is the builder for creating many UserDevice entities in bulk.
type UserDeviceCreateBulk struct {
	config
	err      error
	builders []*UserDeviceCreate
	conflict []sql.ConflictOption
}

// Save creates the UserDevice entities in the database.
func (_c *UserDeviceCreateBulk) Save(ctx context.Context) ([]*UserDevice, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserDevice, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserDeviceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserDeviceCreateBulk) SaveX(ctx context.Context) []*UserDevice {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserDeviceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserDeviceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserDevice.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserDeviceUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserDeviceCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserDeviceUpsertBulk {
	_c.conflict = opts
	return &UserDeviceUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserDevice.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserDeviceCreateBulk) OnConflictColumns(columns ...string) *UserDeviceUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserDeviceUpsertBulk{
		create: _c,
	}
}

// UserDeviceUpsertBulk is the builder for "upsert"-ing
// a bulk of UserDevice nodes.
type UserDeviceUpsertBulk struct {
	create *UserDeviceCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserDevice.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(userdevice.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *UserDeviceUpsertBulk) UpdateNewValues() *UserDeviceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(userdevice.FieldID)
			}
			if _, exists := b.mutation.UserID(); exists {
				s.SetIgnore(userdevice.FieldUserID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserDevice.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserDeviceUpsertBulk) Ignore() *UserDeviceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserDeviceUpsertBulk) DoNothing() *UserDeviceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserDeviceCreateBulk.OnConflict
// documentation for more info.
func (u *UserDeviceUpsertBulk) Update(set func(*UserDeviceUpsert)) *UserDeviceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserDeviceUpsert{UpdateSet: update})
	}))
	return u
}

// SetDeviceUID sets the "device_uid" field.
func (u *UserDeviceUpsertBulk) SetDeviceUID(v string) *UserDeviceUpsertBulk {
	return u.Update(func(s *UserDeviceUpsert) {
		s.SetDeviceUID(v)
	})
}

// UpdateDeviceUID sets the "device_uid" field to the value that was provided on create.
func (u *UserDeviceUpsertBulk) UpdateDeviceUID() *UserDeviceUpsertBulk {
	return u.Update(func(s *UserDeviceUpsert) {
		s.UpdateDeviceUID()
	})
}

// SetDeviceName sets the "device_name" field.
func (u *UserDeviceUpsertBulk) SetDeviceName(v string) *UserDeviceUpsertBulk {
	return u.Update(func(s *UserDeviceUpsert) {
		s.SetDeviceName(v)
	})
}

// UpdateDeviceName sets the "device_name" field to the value that was provided on create.
func (u *UserDeviceUpsertBulk) UpdateDeviceName() *UserDeviceUpsertBulk {
	return u.Update(func(s *UserDeviceUpsert) {
		s.UpdateDeviceName()
	})
}

// ClearDeviceName clears the value of the "device_name" field.
func (u *UserDeviceUpsertBulk) ClearDeviceName() *UserDeviceUpsertBulk {
	return u.Update(func(s *UserDeviceUpsert) {
		s.ClearDeviceName()
	})
}

// SetSystemName sets the "system_name" field.
func (u *UserDeviceUpsertBulk) SetSystemName(v string) *UserDeviceUpsertBulk {
	return u.Update(func(s *UserDeviceUpsert) {
		s.SetSystemName(v)
	})
}

// UpdateSystemName sets the "system_name" field to the value that was provided on create.
func (u *UserDeviceUpsertBulk) UpdateSystemName() *UserDeviceUpsertBulk {
	return u.Update(func(s *UserDeviceUpsert) {
		s.UpdateSystemName()
	})
}

// ClearSystemName clears the value of the "system_name" field.
func (u *UserDeviceUpsertBulk) ClearSystemName() *UserDeviceUpsertBulk {
	return u.Update(func(s *UserDeviceUpsert) {
		s.ClearSystemName()
	})
}

// SetSystemVersion sets the "system_version" field.
func (u *UserDeviceUpsertBulk) SetSystemVersion(v string) *UserDeviceUpsertBulk {
	return u.Update(func(s *UserDeviceUpsert) {
		s.SetSystemVersion(v)
	})
}

// UpdateSystemVersion sets the "system_version" field to the value that was provided on create.
func (u *UserDeviceUpsertBulk) UpdateSystemVersion() *UserDeviceUpsertBulk {
	return u.Update(func(s *UserDeviceUpsert) {
		s.UpdateSystemVersion()
	})
}

// ClearSystemVersion clears the value of the "system_version" field.
func (u *UserDeviceUpsertBulk) ClearSystemVersion() *UserDeviceUpsertBulk {
	return u.Update(func(s *UserDeviceUpsert) {
		s.ClearSystemVersion()
	})
}

// SetAppVersion sets the "app_version" field.
func (u *UserDeviceUpsertBulk) SetAppVersion(v string) *UserDeviceUpsertBulk {
	return u.Update(func(s *UserDeviceUpsert) {
		s.SetAppVersion(v)
	})
}

// UpdateAppVersion sets the "app_version" field to the value that was provided on create.
func (u *UserDeviceUpsertBulk) UpdateAppVersion() *UserDeviceUpsertBulk {
	return u.Update(func(s *UserDeviceUpsert) {
		s.UpdateAppVersion()
	})
}

// ClearAppVersion clears the value of the "app_version" field.
func (u *UserDeviceUpsertBulk) ClearAppVersion() *UserDeviceUpsertBulk {
	return u.Update(func(s *UserDeviceUpsert) {
		s.ClearAppVersion()
	})
}

// SetDeviceModel sets the "device_model" field.
func (u *UserDeviceUpsertBulk) SetDeviceModel(v string) *UserDeviceUpsertBulk {
	return u.Update(func(s *UserDeviceUpsert) {
		s.SetDeviceModel(v)
	})
}

// UpdateDeviceModel sets the "device_model" field to the value that was provided on create.
func (u *UserDeviceUpsertBulk) UpdateDeviceModel() *UserDeviceUpsertBulk {
	return u.Update(func(s *UserDeviceUpsert) {
		s.UpdateDeviceModel()
	})
}

// ClearDeviceModel clears the value of the "device_model" field.
func (u *UserDeviceUpsertBulk) ClearDeviceModel() *UserDeviceUpsertBulk {
	return u.Update(func(s *UserDeviceUpsert) {
		s.ClearDeviceModel()
	})
}

// SetStatus sets the "status" field.
func (u *UserDeviceUpsertBulk) SetStatus(v typex.SimpleStatus) *UserDeviceUpsertBulk {
	return u.Update(func(s *UserDeviceUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UserDeviceUpsertBulk) UpdateStatus() *UserDeviceUpsertBulk {
	return u.Update(func(s *UserDeviceUpsert) {
		s.UpdateStatus()
	})
}

// ClearStatus clears the value of the "status" field.
func (u *UserDeviceUpsertBulk) ClearStatus() *UserDeviceUpsertBulk {
	return u.Update(func(s *UserDeviceUpsert) {
		s.ClearStatus()
	})
}

// Exec executes the query.
func (u *UserDeviceUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserDeviceCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserDeviceCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserDeviceUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
