appName: msgcenter
version: 0.0.1
development: true
log:
  withTraceID: true
  traceIDKey: "traceId"
  cores:
    - level: debug
      outputPaths:
        - stdout
      encoderConfig:
        timeKey: "@timestamp"
        messageKey: "message"
        callerKey: "file"
  rotate:
    maxsize: 10
    maxage: 10
    maxbackups: 20
    localtime: true

web:
  server:
    addr: 127.0.0.1:10070
  engine:
    routerGroups:
      - alertmanager:
          basePath: "/api/v2"
          middlewares:
            - accessLog:
            - recovery:
            - errorHandle:
      - graphql:
          basePath: "/graphql"
          middlewares:
            - accessLog:
                exclude:
                  - IntrospectionQuery
            - recovery:
            - errorHandle:
            - jwt:
                signingMethod: "HS256"
                signingKey: "secret"
                exclude:
                  - "/graphql" #doc page
            - tenant:
                lookup: "header:X-Tenant-ID,query:X-Tenant-Id" ## browser may be transfer query ID to Id
            - graphql:
                group: "/graphql"
                withAuthorization: false
                appCode: "msg"
store:
  msgcenter:
    driverName: mysql
    dsn: "root:@tcp(localhost:3306)/msgcenter?parseTime=true&loc=Local"

entcache:
  level: context

alertManager:
  # 集群配置,如无配置表示单机模式
  cluster:
    options:
      # 指定集群中的节点,可以是服务名或者IP
      known: ["localhost"]
    memberList:
      bindAddr: 0.0.0.0
      bindPort: 7946
  config:
    # 如果指定租户，则只能访问指定租户的配置
    tenants: [1,2,3]
    file: etc/alertmanager.yaml
  storage:
    path: data
  data:
    retention: 120h
    maintenanceInterval: 15m
  alerts:
    gcInterval: 30m
  template:
    path: ../../test/testdata/tpl # path for custom template

prometheus:
  server:
    addr: 127.0.0.1:9093
